using LuxMap.Shared.Authorization;

namespace LuxMap.Modules.Faults.Entities;

/// <summary>
/// A group of faults that share ONE electrical cause. Its ID looks like <c>CLS-001</c>
/// (Contract section 0.2).
/// </summary>
/// <remarks>
/// A tripped breaker or a broken conductor propagates along the CIRCUIT, so a scatter of dark poles
/// is one <c>segment_outage</c> rather than N lamp faults — CLAUDE.md states this as a rule, and it
/// is the reason a cluster is a thing at all.
/// <para>
/// <b>A table, not a bare <c>text</c> column on <c>fault</c>.</b> Contract section 2.4 only ever
/// filters on <c>cluster_id</c>, so a plain column would satisfy the endpoint — but it would also be
/// the second unconstrained id in the schema, alongside <c>pole_current_status.last_sweep_id</c>,
/// with nothing to notice a value pointing at a cluster that never existed. It also gives the
/// clustering run somewhere to record itself: BE-34 has to answer which model version produced a
/// given result, and a column cannot hold that.
/// </para>
/// <para>
/// ⚠️ Nothing writes rows here yet. CV-15 does the clustering, and it depends on BE-13 (assigning
/// poles to feeders), which has not been built. This is the shape those will write into.
/// </para>
/// </remarks>
public class FaultCluster : ICommuneScoped
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string ClusterId { get; set; } = null!;

    /// <summary>
    /// The road segment the outage was reported against.
    /// </summary>
    /// <remarks>
    /// Segment rather than feeder, even though the cause travels along the circuit: section 2.3
    /// publishes <c>has_active_segment_fault</c> per segment, and that is what the front end
    /// highlights. The feeder is reachable through the poles.
    /// </remarks>
    public required string SegmentId { get; set; }

    /// <summary>Denormalised from the segment. Without it the cluster escapes Contract section 7 entirely.</summary>
    public required string CommuneId { get; set; }

    public DateTime ClusteredAt { get; set; }

    /// <summary>
    /// Which version of the clustering model produced this grouping (BE-34).
    /// </summary>
    /// <remarks>
    /// Nullable because nothing sets it yet. CLAUDE.md: a detection that cannot be reproduced is not
    /// a result, so the column exists from the first migration rather than being retrofitted once
    /// rows already exist without it.
    /// </remarks>
    public string? ClusteringModelVersion { get; set; }

    public DateTime CreatedAt { get; set; }
}
