using LuxMap.Persistence.Audit;
using LuxMap.Shared.Authorization;
using LuxMap.Shared.Contracts.Enums;

namespace LuxMap.Modules.Faults.Entities;

/// <summary>
/// One lighting fault. Its ID looks like <c>FAULT-0001</c> (Contract section 0.2).
/// </summary>
/// <remarks>
/// Faults arrive from three channels — CV over sweep imagery, IoT telemetry, and a survey crew
/// reporting on site — and <see cref="SourceChannel"/> is what separates them. All three enter at
/// <see cref="FaultStatus.Detected"/>: Contract section 2.8 is explicit that a fault reported by a
/// person still goes through the same review as one the engine found. Nobody creates an
/// already-confirmed fault.
/// <para>
/// These columns record the latest decision only. D-R13 requires the full sequence in the
/// shared append-only audit_event table (BE-23a), not a separate FaultHistory table.
/// Work order propagation is audited in its single work order event; BE-19 owns direct decisions.
/// </para>
/// </remarks>
public class Fault : ICommuneScoped, IAudited
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string FaultId { get; set; } = null!;

    /// <summary>
    /// De-duplication key for offline reporting (Contract section 5.8). NULL for engine-generated
    /// faults, which have no client and no retry.
    /// </summary>
    /// <remarks>
    /// Unique through a PARTIAL index — many engine faults share NULL, and a plain unique index
    /// would be satisfied by that anyway in PostgreSQL, but the filter says the intent out loud.
    /// </remarks>
    public string? ClientOpId { get; set; }

    /// <summary>
    /// The pole, when it is known. NULL when a crew reports a fault at a pole not yet in the asset
    /// records (Contract section 2.8).
    /// </summary>
    public string? PoleId { get; set; }

    /// <summary>Only when the pole carries several lamps and the crew knows which one.</summary>
    public string? FixtureId { get; set; }

    /// <summary>Denormalised from the pole where there is one; set directly for a segment-level fault.</summary>
    public string? SegmentId { get; set; }

    /// <summary>
    /// The commune this fault belongs to. NOT NULL — see the remarks.
    /// </summary>
    /// <remarks>
    /// Two sources, because <see cref="PoleId"/> is nullable:
    /// <list type="number">
    /// <item>With a pole, the server reads it from the pole. The write guard checks that a commune is
    /// inside the caller's scope; it does NOT check that it matches the pole's, so a client-supplied
    /// value could pass both checks and still file the fault under the wrong commune.</item>
    /// <item>Without a pole, it comes from the caller's JWT scope. <c>administrative_unit</c> carries
    /// no boundary geometry — deliberately, Branch C has no source for real boundaries — so deriving
    /// it from <c>lat</c>/<c>lng</c> is not possible.</item>
    /// </list>
    /// A caller scoped to several communes has to say which, since neither source can decide for
    /// them. Registered as drift: Contract section 2.8 has no <c>commune_id</c> in the body.
    /// </remarks>
    public required string CommuneId { get; set; }

    /// <summary>
    /// Where it is. Required when <see cref="PoleId"/> is NULL, enforced by a table CHECK.
    /// </summary>
    /// <remarks>
    /// Plain columns rather than <c>geometry(Point,4326)</c>: Contract section 2.4 publishes
    /// <c>location { lat, lng }</c> as two numbers and <c>GET /faults</c> is explicitly NOT GeoJSON,
    /// so nothing here is queried spatially. A geometry column would invite a GIST index and the
    /// distance rules of BE-10 for a value that is only ever read back.
    /// </remarks>
    public double? Lat { get; set; }

    public double? Lng { get; set; }

    /// <summary>
    /// The type as the reporting channel gave it. Never changed after insert — a Manager's
    /// correction goes to <see cref="OverrideFaultType"/> (BE-19 D-4).
    /// </summary>
    /// <remarks>
    /// Not ground truth: under registration v1.4 a <c>lamp_dim</c> comes from CV ON/OFF plus the
    /// per-pole lux peak. Kept so "what the pipeline said" and "what the Manager decided" can both be
    /// read without digging through audit JSON.
    /// </remarks>
    public FaultType FaultType { get; set; }

    /// <summary>
    /// The Manager's reclassification, <c>lamp_out</c> ↔ <c>lamp_dim</c> only; NULL = none. The API's
    /// <c>fault_type</c> is <c>override_fault_type ?? fault_type</c> (<see cref="EffectiveType"/>).
    /// </summary>
    public FaultType? OverrideFaultType { get; set; }

    /// <summary>The type the API reports and filters on.</summary>
    public FaultType EffectiveType => OverrideFaultType ?? FaultType;

    /// <summary>The Manager's latest review note (BE-19 D-6). Separate from <see cref="Note"/>, the reporter's words.</summary>
    public string? ReviewNote { get; set; }

    public FaultStatus FaultStatus { get; set; }

    public Severity Severity { get; set; }

    /// <summary>Which channel detected it. A different axis from <see cref="DataSource"/>.</summary>
    public SourceChannel SourceChannel { get; set; }

    public DataSource DataSource { get; set; }

    /// <summary>
    /// Ranking score computed by CV-16. Nullable, because CV-16 is a separate process that may not
    /// have run yet.
    /// </summary>
    /// <remarks>
    /// A stored column rather than something computed per query. Contract section 2.4 makes the
    /// default order <c>-priority_score</c>, and ordering by an expression cannot use an index and
    /// gives unstable pages. It also has to be storable at all: the Contract says CV-16 computes it,
    /// and a value produced outside the API needs somewhere to land.
    /// <para>
    /// ⚠️ The cost is that changing the weights (BE-33) means recomputing the column for every row.
    /// That job belongs to BE-26; recorded in CLAUDE.md.
    /// </para>
    /// </remarks>
    public double? PriorityScore { get; set; }

    /// <summary>0..1 when present, enforced by CHECK. NULL when the channel reports no confidence.</summary>
    public double? StatusConfidence { get; set; }

    /// <summary>Set by CV-15 when this fault turns out to share one electrical cause with others.</summary>
    public string? ClusterId { get; set; }

    public DateTime DetectedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    /// <summary>Free text. Required from a human reporter (section 2.8), absent from engine faults.</summary>
    public string? Note { get; set; }

    // ── Audit trail ─────────────────────────────────────────────────────────

    /// <summary>
    /// Who reported it, from the JWT. NULL for CV and IoT faults.
    /// </summary>
    /// <remarks>
    /// ⚠️ NULL here is not missing data — it is the accurate answer. An engine fault has no reporter,
    /// and <see cref="SourceChannel"/> already says which engine. A synthetic system account would
    /// make every row look uniform while recording something that never happened, and would then
    /// appear in any listing of who reports faults.
    /// </remarks>
    public string? ReportedBy { get; set; }

    /// <summary>The engineer who confirmed or rejected it (Contract section 2.5).</summary>
    public string? ConfirmedBy { get; set; }

    public DateTime? ConfirmedAt { get; set; }

    /// <summary>Who marked the work done.</summary>
    public string? ResolvedBy { get; set; }

    public DateTime? ResolvedAt { get; set; }

    /// <summary>
    /// Which model version produced an automatic detection (BE-34).
    /// </summary>
    /// <remarks>
    /// Nullable, and NULL for anything a person reported. CLAUDE.md: an automatic detection that
    /// cannot be traced to a model version is not reproducible, and reproducibility is a requirement
    /// of the study rather than a nicety. The column exists from the first migration so BE-34 is not
    /// left retrofitting it onto rows that already lost the information.
    /// </remarks>
    public string? DetectionModelVersion { get; set; }

    public DateTime CreatedAt { get; set; }

    public uint Version { get; set; }
}
