namespace LuxMap.Shared.Contracts;

/// <summary>
/// The Contract's ID convention (sections 0.1–0.4): <c>&lt;PREFIX&gt;-&lt;zero-padded number&gt;</c>,
/// generated by a PostgreSQL sequence and formatted in the database itself.
/// </summary>
/// <param name="Prefix">Uppercase; see the table in Contract section 0.2.</param>
/// <param name="Digits">Padding width: 4 for high-volume entities, 3 for low-volume, 6 for frames and detections.</param>
/// <param name="SequenceName">The Postgres sequence name, snake_case per Contract section 5.1.</param>
public sealed record PrefixedIdSpec(string Prefix, int Digits, string SequenceName)
{
    /// <summary>
    /// The database function that formats the ID. It exists because the obvious expression is wrong:
    /// PostgreSQL's <c>lpad(string, length, fill)</c> <b>TRUNCATES</b> when the string is already
    /// longer than <c>length</c>, so <c>lpad('10000', 4, '0')</c> is <c>'1000'</c> — the 10000th pole
    /// would be handed <c>POLE-1000</c> and collide with the 1000th.
    /// <para>
    /// Contract section 0.3 requires the opposite: past the padding width the ID simply grows.
    /// <c>greatest(digits, length(...))</c> delivers that, but it names the value three times, and
    /// PostgreSQL allows neither a subquery nor a CTE inside a column <c>DEFAULT</c> — so a function
    /// is what keeps <c>nextval</c> evaluated exactly ONCE per row.
    /// </para>
    /// </summary>
    public const string FormatFunction = "luxmap_format_id";

    /// <summary>
    /// SQL for the column's <c>DEFAULT</c>. <c>nextval</c> is VOLATILE, so the whole expression is
    /// evaluated per row and never constant-folded, even though the function itself is IMMUTABLE.
    /// </summary>
    public string DefaultValueSql
        => $"{FormatFunction}('{Prefix}', nextval('{SequenceName}'), {Digits})";

    /// <summary>
    /// Builds an ID by hand — for tests and assertions only; real writes are generated by the database.
    /// </summary>
    /// <remarks>
    /// <see cref="string.PadLeft(int, char)"/> never truncates, so this side was always right; it is
    /// <see cref="DefaultValueSql"/> that had to be brought into line with it.
    /// </remarks>
    public string Format(long value) => $"{Prefix}-{value.ToString().PadLeft(Digits, '0')}";
}

/// <summary>
/// The full prefix table from Contract section 0.2. All 16 rows are declared up front so that from
/// BE-09 onward nobody retypes a prefix or a padding width — one typo corrupts every ID of that
/// entity.
/// </summary>
/// <remarks>
/// <c>LuminanceBaseline</c> and <c>TelemetryReading</c> are deliberately absent: Contract section
/// 0.2 states they carry no display ID and are keyed by <c>(pole_id, ...)</c> and
/// <c>(node_id, reading_time)</c>. <c>RefreshToken</c> is absent too — it never reaches the client.
/// </remarks>
public static class PrefixedIds
{
    public static readonly PrefixedIdSpec Pole = new("POLE", 4, "pole_id_seq");
    public static readonly PrefixedIdSpec Fault = new("FAULT", 4, "fault_id_seq");
    public static readonly PrefixedIdSpec RoadSegment = new("SEG", 3, "segment_id_seq");
    public static readonly PrefixedIdSpec AdministrativeUnit = new("COM", 3, "commune_id_seq");
    public static readonly PrefixedIdSpec Fixture = new("FIX", 4, "fixture_id_seq");
    public static readonly PrefixedIdSpec Feeder = new("FDR", 3, "feeder_id_seq");
    public static readonly PrefixedIdSpec IotNode = new("NODE", 3, "node_id_seq");
    public static readonly PrefixedIdSpec SurveySweep = new("SWP", 3, "sweep_id_seq");
    public static readonly PrefixedIdSpec SurveyFrame = new("FRM", 6, "frame_id_seq");
    public static readonly PrefixedIdSpec Detection = new("DET", 6, "detection_id_seq");
    public static readonly PrefixedIdSpec LuxReading = new("LUX", 4, "lux_id_seq");
    public static readonly PrefixedIdSpec WorkOrder = new("WO", 4, "work_order_id_seq");
    public static readonly PrefixedIdSpec RepairEvidence = new("EVD", 4, "evidence_id_seq");
    public static readonly PrefixedIdSpec ExternalUnit = new("EXT", 3, "external_unit_id_seq");
    public static readonly PrefixedIdSpec AppUser = new("USR", 3, "user_id_seq");
    public static readonly PrefixedIdSpec FaultCluster = new("CLS", 3, "cluster_id_seq");

    public static IReadOnlyList<PrefixedIdSpec> All { get; } =
    [
        Pole, Fault, RoadSegment, AdministrativeUnit, Fixture, Feeder, IotNode, SurveySweep,
        SurveyFrame, Detection, LuxReading, WorkOrder, RepairEvidence, ExternalUnit, AppUser, FaultCluster,
    ];
}
