// <auto-generated />
using System;
using LuxMap.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LuxMap.Persistence.Migrations
{
    [DbContext(typeof(LuxMapDbContext))]
    [Migration("20260901091555_AddCommuneForeignKeys")]
    partial class AddCommuneForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("commune_id_seq");

            modelBuilder.HasSequence("feeder_id_seq");

            modelBuilder.HasSequence("fixture_id_seq");

            modelBuilder.HasSequence("pole_id_seq");

            modelBuilder.HasSequence("segment_id_seq");

            modelBuilder.HasSequence("user_id_seq");

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Feeder", b =>
                {
                    b.Property<string>("FeederId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("feeder_id")
                        .HasDefaultValueSql("luxmap_format_id('FDR', nextval('feeder_id_seq'), 3)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "feeder_id_seq");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FeederName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feeder_name");

                    b.Property<LineString>("Geom")
                        .HasColumnType("geometry(LineString,4326)")
                        .HasColumnName("geom");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FeederId")
                        .HasName("pk_feeder");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_feeder_commune_id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_feeder_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.ToTable("feeder", (string)null);

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Fixture", b =>
                {
                    b.Property<string>("FixtureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("fixture_id")
                        .HasDefaultValueSql("luxmap_format_id('FIX', nextval('fixture_id_seq'), 4)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "fixture_id_seq");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<string>("FixtureType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fixture_type");

                    b.Property<DateOnly>("InstallDate")
                        .HasColumnType("date")
                        .HasColumnName("install_date");

                    b.Property<int>("LampWatt")
                        .HasColumnType("integer")
                        .HasColumnName("lamp_watt");

                    b.Property<string>("PoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pole_id");

                    b.Property<string>("PowerSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("power_source");

                    b.Property<DateOnly?>("RemovedDate")
                        .HasColumnType("date")
                        .HasColumnName("removed_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("WarrantyExpiry")
                        .HasColumnType("date")
                        .HasColumnName("warranty_expiry");

                    b.HasKey("FixtureId")
                        .HasName("pk_fixture");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_fixture_commune_id");

                    b.HasIndex("PoleId")
                        .HasDatabaseName("ix_fixture_pole_id_active")
                        .HasFilter("removed_date IS NULL");

                    b.ToTable("fixture", null, t =>
                        {
                            t.HasCheckConstraint("ck_fixture_data_source", "\"data_source\" IN ('field', 'public_imagery', 'calibration_rig', 'simulated')");

                            t.HasCheckConstraint("ck_fixture_fixture_type", "\"fixture_type\" IN ('led_road_lamp', 'solar_all_in_one')");

                            t.HasCheckConstraint("ck_fixture_power_source", "\"power_source\" IN ('grid', 'solar')");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Pole", b =>
                {
                    b.Property<string>("PoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("pole_id")
                        .HasDefaultValueSql("luxmap_format_id('POLE', nextval('pole_id_seq'), 4)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "pole_id_seq");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<string>("FeederId")
                        .HasColumnType("text")
                        .HasColumnName("feeder_id");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("geom");

                    b.Property<bool>("NearSensitivePoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("near_sensitive_poi");

                    b.Property<string>("SegmentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("segment_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PoleId")
                        .HasName("pk_pole");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_pole_commune_id");

                    b.HasIndex("FeederId")
                        .HasDatabaseName("ix_pole_feeder_id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_pole_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("SegmentId")
                        .HasDatabaseName("ix_pole_segment_id");

                    b.ToTable("pole", null, t =>
                        {
                            t.HasCheckConstraint("ck_pole_data_source", "\"data_source\" IN ('field', 'public_imagery', 'calibration_rig', 'simulated')");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.PoleCurrentStatus", b =>
                {
                    b.Property<string>("PoleId")
                        .HasColumnType("text")
                        .HasColumnName("pole_id");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<string>("FixtureStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fixture_status");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("LastSweepId")
                        .HasColumnType("text")
                        .HasColumnName("last_sweep_id");

                    b.Property<double?>("StatusConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("status_confidence");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PoleId")
                        .HasName("pk_pole_current_status");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_pole_current_status_commune_id");

                    b.ToTable("pole_current_status", null, t =>
                        {
                            t.HasCheckConstraint("ck_pole_current_status_confidence_matches_status", "(status_confidence IS NULL) = (fixture_status = 'unknown')");

                            t.HasCheckConstraint("ck_pole_current_status_fixture_status", "\"fixture_status\" IN ('normal', 'dim', 'out', 'unknown')");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.RoadSegment", b =>
                {
                    b.Property<string>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("segment_id")
                        .HasDefaultValueSql("luxmap_format_id('SEG', nextval('segment_id_seq'), 3)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "segment_id_seq");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<LineString>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(LineString,4326)")
                        .HasColumnName("geom");

                    b.Property<int>("LengthM")
                        .HasColumnType("integer")
                        .HasColumnName("length_m");

                    b.Property<string>("RoadClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("road_class");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("segment_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SegmentId")
                        .HasName("pk_road_segment");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_road_segment_commune_id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_road_segment_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.ToTable("road_segment", null, t =>
                        {
                            t.HasCheckConstraint("ck_road_segment_data_source", "\"data_source\" IN ('field', 'public_imagery', 'calibration_rig', 'simulated')");

                            t.HasCheckConstraint("ck_road_segment_road_class", "\"road_class\" IN ('inter_commune', 'inter_village')");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUser", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("luxmap_format_id('USR', nextval('user_id_seq'), 3)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "user_id_seq");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("HasSystemWideScope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_system_wide_scope");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<string>("PasswordAlgorithm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_algorithm");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_username");

                    b.ToTable("app_user", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_user_role", "\"role\" IN ('management_agency', 'maintenance_engineer', 'field_crew', 'administrator')");
                        });
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUserCommune", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("CommuneId")
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "CommuneId")
                        .HasName("pk_app_user_commune");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_app_user_commune_commune_id");

                    b.ToTable("app_user_commune", (string)null);
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChainAbsoluteExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("chain_absolute_expiry");

                    b.Property<Guid>("ChainId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long?>("ReplacedByTokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("ChainId")
                        .HasDatabaseName("ix_refresh_token_chain_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_token_expires_at");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_token_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_token_revoked_reason", "\"revoked_reason\" IS NULL OR \"revoked_reason\" IN ('rotation', 'logout', 'reuse_detected')");
                        });
                });

            modelBuilder.Entity("LuxMap.Persistence.AdministrativeUnit", b =>
                {
                    b.Property<string>("CommuneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("commune_id")
                        .HasDefaultValueSql("luxmap_format_id('COM', nextval('commune_id_seq'), 3)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "commune_id_seq");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SeedKey")
                        .HasColumnType("text")
                        .HasColumnName("seed_key");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CommuneId")
                        .HasName("pk_administrative_unit");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_administrative_unit_name");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("ix_administrative_unit_seed_key");

                    b.ToTable("administrative_unit", (string)null);
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Feeder", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feeder_administrative_unit_commune_id");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Fixture", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fixture_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Assets.Entities.Pole", "Pole")
                        .WithMany("Fixtures")
                        .HasForeignKey("PoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fixture_pole_pole_id");

                    b.Navigation("Pole");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Pole", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pole_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Assets.Entities.Feeder", "Feeder")
                        .WithMany("Poles")
                        .HasForeignKey("FeederId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pole_feeder_feeder_id");

                    b.HasOne("LuxMap.Modules.Assets.Entities.RoadSegment", "Segment")
                        .WithMany("Poles")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pole_road_segment_segment_id");

                    b.Navigation("Feeder");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.PoleCurrentStatus", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pole_current_status_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Assets.Entities.Pole", "Pole")
                        .WithOne("CurrentStatus")
                        .HasForeignKey("LuxMap.Modules.Assets.Entities.PoleCurrentStatus", "PoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pole_current_status_pole_pole_id");

                    b.Navigation("Pole");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.RoadSegment", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_road_segment_administrative_unit_commune_id");
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUserCommune", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", "Commune")
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_commune_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", "User")
                        .WithMany("CommuneAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_commune_app_user_user_id");

                    b.Navigation("Commune");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("LuxMap.Modules.Identity.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_token_refresh_token_replaced_by_token_id");

                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_app_user_user_id");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Feeder", b =>
                {
                    b.Navigation("Poles");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Pole", b =>
                {
                    b.Navigation("CurrentStatus");

                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.RoadSegment", b =>
                {
                    b.Navigation("Poles");
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUser", b =>
                {
                    b.Navigation("CommuneAssignments");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
