// <auto-generated />
using System;
using LuxMap.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LuxMap.Persistence.Migrations
{
    [DbContext(typeof(LuxMapDbContext))]
    [Migration("20260831061451_AddCaseInsensitiveIdentityIndexes")]
    partial class AddCaseInsensitiveIdentityIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("commune_id_seq");

            modelBuilder.HasSequence("user_id_seq");

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AdministrativeUnit", b =>
                {
                    b.Property<string>("CommuneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("commune_id")
                        .HasDefaultValueSql("'COM-' || LPAD(nextval('commune_id_seq')::text, 3, '0')")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "commune_id_seq");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CommuneId")
                        .HasName("pk_administrative_unit");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_administrative_unit_name");

                    b.ToTable("administrative_unit", (string)null);
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUser", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("'USR-' || LPAD(nextval('user_id_seq')::text, 3, '0')")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "user_id_seq");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("HasSystemWideScope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_system_wide_scope");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<string>("PasswordAlgorithm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_algorithm");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_username");

                    b.ToTable("app_user", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_user_role", "\"role\" IN ('management_agency', 'maintenance_engineer', 'field_crew', 'administrator')");
                        });
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUserCommune", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("CommuneId")
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "CommuneId")
                        .HasName("pk_app_user_commune");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_app_user_commune_commune_id");

                    b.ToTable("app_user_commune", (string)null);
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChainAbsoluteExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("chain_absolute_expiry");

                    b.Property<Guid>("ChainId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long?>("ReplacedByTokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("ChainId")
                        .HasDatabaseName("ix_refresh_token_chain_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_token_expires_at");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_token_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_token_revoked_reason", "\"revoked_reason\" IS NULL OR \"revoked_reason\" IN ('rotation', 'logout', 'reuse_detected')");
                        });
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUserCommune", b =>
                {
                    b.HasOne("LuxMap.Modules.Identity.Entities.AdministrativeUnit", "Commune")
                        .WithMany("UserAssignments")
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_commune_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", "User")
                        .WithMany("CommuneAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_commune_app_user_user_id");

                    b.Navigation("Commune");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("LuxMap.Modules.Identity.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_token_refresh_token_replaced_by_token_id");

                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_app_user_user_id");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AdministrativeUnit", b =>
                {
                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUser", b =>
                {
                    b.Navigation("CommuneAssignments");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
