// <auto-generated />
using System;
using LuxMap.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LuxMap.Persistence.Migrations
{
    [DbContext(typeof(LuxMapDbContext))]
    [Migration("20260929125521_AddFaultReview")]
    partial class AddFaultReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("cluster_id_seq");

            modelBuilder.HasSequence("commune_id_seq");

            modelBuilder.HasSequence("fault_id_seq");

            modelBuilder.HasSequence("feeder_id_seq");

            modelBuilder.HasSequence("fixture_id_seq");

            modelBuilder.HasSequence("lux_id_seq");

            modelBuilder.HasSequence("node_id_seq");

            modelBuilder.HasSequence("pole_id_seq");

            modelBuilder.HasSequence("segment_id_seq");

            modelBuilder.HasSequence("user_id_seq");

            modelBuilder.HasSequence("work_order_id_seq");

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Feeder", b =>
                {
                    b.Property<string>("FeederId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("feeder_id")
                        .HasDefaultValueSql("luxmap_format_id('FDR', nextval('feeder_id_seq'), 3)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "feeder_id_seq");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("text")
                        .HasColumnName("external_ref");

                    b.Property<string>("FeederName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feeder_name");

                    b.Property<LineString>("Geom")
                        .HasColumnType("geometry(LineString,4326)")
                        .HasColumnName("geom");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FeederId")
                        .HasName("pk_feeder");

                    b.HasAlternateKey("FeederId", "CommuneId")
                        .HasName("ak_feeder_feeder_id_commune_id");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_feeder_commune_id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_feeder_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("CommuneId", "ExternalRef")
                        .IsUnique()
                        .HasDatabaseName("ux_feeder_commune_external_ref")
                        .HasFilter("external_ref IS NOT NULL");

                    b.ToTable("feeder", (string)null);

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Fixture", b =>
                {
                    b.Property<string>("FixtureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("fixture_id")
                        .HasDefaultValueSql("luxmap_format_id('FIX', nextval('fixture_id_seq'), 4)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "fixture_id_seq");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<string>("FixtureType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fixture_type");

                    b.Property<DateOnly>("InstallDate")
                        .HasColumnType("date")
                        .HasColumnName("install_date");

                    b.Property<int>("LampWatt")
                        .HasColumnType("integer")
                        .HasColumnName("lamp_watt");

                    b.Property<string>("PoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pole_id");

                    b.Property<string>("PowerSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("power_source");

                    b.Property<DateOnly?>("RemovedDate")
                        .HasColumnType("date")
                        .HasColumnName("removed_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("WarrantyExpiry")
                        .HasColumnType("date")
                        .HasColumnName("warranty_expiry");

                    b.HasKey("FixtureId")
                        .HasName("pk_fixture");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_fixture_commune_id");

                    b.HasIndex("PoleId")
                        .IsUnique()
                        .HasDatabaseName("ux_fixture_pole_id_active")
                        .HasFilter("removed_date IS NULL");

                    b.ToTable("fixture", null, t =>
                        {
                            t.HasCheckConstraint("ck_fixture_data_source", "\"data_source\" IN ('field', 'public_imagery', 'calibration_rig', 'simulated')");

                            t.HasCheckConstraint("ck_fixture_fixture_type", "\"fixture_type\" IN ('led_road_lamp')");

                            t.HasCheckConstraint("ck_fixture_power_source", "\"power_source\" IN ('grid')");

                            t.HasCheckConstraint("ck_fixture_removed_after_install", "removed_date IS NULL OR removed_date >= install_date");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Pole", b =>
                {
                    b.Property<string>("PoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("pole_id")
                        .HasDefaultValueSql("luxmap_format_id('POLE', nextval('pole_id_seq'), 4)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "pole_id_seq");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("text")
                        .HasColumnName("external_ref");

                    b.Property<string>("FeederId")
                        .HasColumnType("text")
                        .HasColumnName("feeder_id");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("geom");

                    b.Property<bool>("NearSensitivePoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("near_sensitive_poi");

                    b.Property<string>("SegmentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("segment_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PoleId")
                        .HasName("pk_pole");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_pole_commune_id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_pole_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("SegmentId")
                        .HasDatabaseName("ix_pole_segment_id");

                    b.HasIndex("CommuneId", "ExternalRef")
                        .IsUnique()
                        .HasDatabaseName("ux_pole_commune_external_ref")
                        .HasFilter("external_ref IS NOT NULL");

                    b.HasIndex("FeederId", "CommuneId")
                        .HasDatabaseName("ix_pole_feeder_id_commune_id");

                    b.ToTable("pole", null, t =>
                        {
                            t.HasCheckConstraint("ck_pole_data_source", "\"data_source\" IN ('field', 'public_imagery', 'calibration_rig', 'simulated')");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.PoleCurrentStatus", b =>
                {
                    b.Property<string>("PoleId")
                        .HasColumnType("text")
                        .HasColumnName("pole_id");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<string>("FixtureStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fixture_status");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("LastSweepId")
                        .HasColumnType("text")
                        .HasColumnName("last_sweep_id");

                    b.Property<double?>("StatusConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("status_confidence");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PoleId")
                        .HasName("pk_pole_current_status");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_pole_current_status_commune_id");

                    b.ToTable("pole_current_status", null, t =>
                        {
                            t.HasCheckConstraint("ck_pole_current_status_confidence_matches_status", "(status_confidence IS NULL) = (fixture_status = 'unknown')");

                            t.HasCheckConstraint("ck_pole_current_status_confidence_range", "status_confidence IS NULL OR (status_confidence >= 0 AND status_confidence <= 1 AND status_confidence <> 'NaN'::float8 AND status_confidence <> 'Infinity'::float8 AND status_confidence <> '-Infinity'::float8)");

                            t.HasCheckConstraint("ck_pole_current_status_fixture_status", "\"fixture_status\" IN ('normal', 'dim', 'out', 'unknown')");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.RoadSegment", b =>
                {
                    b.Property<string>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("segment_id")
                        .HasDefaultValueSql("luxmap_format_id('SEG', nextval('segment_id_seq'), 3)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "segment_id_seq");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("text")
                        .HasColumnName("external_ref");

                    b.Property<LineString>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(LineString,4326)")
                        .HasColumnName("geom");

                    b.Property<int>("LengthM")
                        .HasColumnType("integer")
                        .HasColumnName("length_m");

                    b.Property<string>("RoadClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("road_class");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("segment_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SegmentId")
                        .HasName("pk_road_segment");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_road_segment_commune_id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_road_segment_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("CommuneId", "ExternalRef")
                        .IsUnique()
                        .HasDatabaseName("ux_road_segment_commune_external_ref")
                        .HasFilter("external_ref IS NOT NULL");

                    b.ToTable("road_segment", null, t =>
                        {
                            t.HasCheckConstraint("ck_road_segment_data_source", "\"data_source\" IN ('field', 'public_imagery', 'calibration_rig', 'simulated')");

                            t.HasCheckConstraint("ck_road_segment_road_class", "\"road_class\" IN ('inter_commune', 'inter_village')");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Faults.Entities.Fault", b =>
                {
                    b.Property<string>("FaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("fault_id")
                        .HasDefaultValueSql("luxmap_format_id('FAULT', nextval('fault_id_seq'), 4)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "fault_id_seq");

                    b.Property<string>("ClientOpId")
                        .HasColumnType("text")
                        .HasColumnName("client_op_id");

                    b.Property<string>("ClusterId")
                        .HasColumnType("text")
                        .HasColumnName("cluster_id");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedBy")
                        .HasColumnType("text")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("DetectionModelVersion")
                        .HasColumnType("text")
                        .HasColumnName("detection_model_version");

                    b.Property<string>("FaultStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fault_status");

                    b.Property<string>("FaultType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fault_type");

                    b.Property<string>("FixtureId")
                        .HasColumnType("text")
                        .HasColumnName("fixture_id");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("OverrideFaultType")
                        .HasColumnType("text")
                        .HasColumnName("override_fault_type");

                    b.Property<string>("PoleId")
                        .HasColumnType("text")
                        .HasColumnName("pole_id");

                    b.Property<double?>("PriorityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("priority_score");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("text")
                        .HasColumnName("reported_by");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("text")
                        .HasColumnName("resolved_by");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<string>("SegmentId")
                        .HasColumnType("text")
                        .HasColumnName("segment_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("SourceChannel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_channel");

                    b.Property<double?>("StatusConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("status_confidence");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("FaultId")
                        .HasName("pk_fault");

                    b.HasAlternateKey("FaultId", "CommuneId")
                        .HasName("ak_fault_fault_id_commune_id");

                    b.HasIndex("ClientOpId")
                        .IsUnique()
                        .HasDatabaseName("ux_fault_client_op_id")
                        .HasFilter("client_op_id IS NOT NULL");

                    b.HasIndex("ClusterId")
                        .HasDatabaseName("ix_fault_cluster_id");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_fault_commune_id");

                    b.HasIndex("ConfirmedBy")
                        .HasDatabaseName("ix_fault_confirmed_by");

                    b.HasIndex("FaultStatus")
                        .HasDatabaseName("ix_fault_fault_status");

                    b.HasIndex("FixtureId")
                        .HasDatabaseName("ix_fault_fixture_id");

                    b.HasIndex("PoleId")
                        .HasDatabaseName("ix_fault_pole_id");

                    b.HasIndex("PriorityScore")
                        .IsDescending()
                        .HasDatabaseName("ix_fault_priority_score");

                    b.HasIndex("ReportedBy")
                        .HasDatabaseName("ix_fault_reported_by");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_fault_resolved_by");

                    b.HasIndex("SegmentId")
                        .HasDatabaseName("ix_fault_segment_id");

                    b.ToTable("fault", null, t =>
                        {
                            t.HasCheckConstraint("ck_fault_data_source", "\"data_source\" IN ('field', 'public_imagery', 'calibration_rig', 'simulated')");

                            t.HasCheckConstraint("ck_fault_fault_status", "\"fault_status\" IN ('detected', 'confirmed', 'rejected', 'in_progress', 'resolved', 'verified')");

                            t.HasCheckConstraint("ck_fault_fault_type", "\"fault_type\" IN ('lamp_out', 'lamp_dim', 'segment_outage', 'node_offline', 'runtime_decline')");

                            t.HasCheckConstraint("ck_fault_location_finite", "(lat IS NULL OR (lat <> 'NaN'::float8 AND lat <> 'Infinity'::float8 AND lat <> '-Infinity'::float8 AND lat BETWEEN -90 AND 90)) AND (lng IS NULL OR (lng <> 'NaN'::float8 AND lng <> 'Infinity'::float8 AND lng <> '-Infinity'::float8 AND lng BETWEEN -180 AND 180))");

                            t.HasCheckConstraint("ck_fault_override_fault_type", "\"override_fault_type\" IS NULL OR \"override_fault_type\" IN ('lamp_out', 'lamp_dim', 'segment_outage', 'node_offline', 'runtime_decline')");

                            t.HasCheckConstraint("ck_fault_override_is_lamp_class", "override_fault_type IS NULL OR override_fault_type IN ('lamp_out', 'lamp_dim')");

                            t.HasCheckConstraint("ck_fault_pole_or_location", "pole_id IS NOT NULL OR (lat IS NOT NULL AND lng IS NOT NULL)");

                            t.HasCheckConstraint("ck_fault_priority_score_finite", "priority_score IS NULL OR (priority_score <> 'NaN'::float8 AND priority_score <> 'Infinity'::float8 AND priority_score <> '-Infinity'::float8)");

                            t.HasCheckConstraint("ck_fault_review_note_not_blank", "review_note IS NULL OR btrim(review_note) <> ''");

                            t.HasCheckConstraint("ck_fault_severity", "\"severity\" IN ('low', 'medium', 'high', 'critical')");

                            t.HasCheckConstraint("ck_fault_source_channel", "\"source_channel\" IN ('cv', 'iot', 'field_report')");

                            t.HasCheckConstraint("ck_fault_status_confidence_range", "status_confidence IS NULL OR (status_confidence >= 0 AND status_confidence <= 1 AND status_confidence <> 'NaN'::float8 AND status_confidence <> 'Infinity'::float8 AND status_confidence <> '-Infinity'::float8)");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Faults.Entities.FaultCluster", b =>
                {
                    b.Property<string>("ClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("cluster_id")
                        .HasDefaultValueSql("luxmap_format_id('CLS', nextval('cluster_id_seq'), 3)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "cluster_id_seq");

                    b.Property<DateTime>("ClusteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clustered_at");

                    b.Property<string>("ClusteringModelVersion")
                        .HasColumnType("text")
                        .HasColumnName("clustering_model_version");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SegmentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("segment_id");

                    b.HasKey("ClusterId")
                        .HasName("pk_fault_cluster");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_fault_cluster_commune_id");

                    b.HasIndex("SegmentId")
                        .HasDatabaseName("ix_fault_cluster_segment_id");

                    b.ToTable("fault_cluster", (string)null);

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUser", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("luxmap_format_id('USR', nextval('user_id_seq'), 3)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "user_id_seq");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("HasSystemWideScope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_system_wide_scope");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<string>("PasswordAlgorithm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_algorithm");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_username");

                    b.ToTable("app_user", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_user_role", "\"role\" IN ('superior', 'manager', 'field_engineer', 'system_admin')");
                        });
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUserCommune", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("CommuneId")
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "CommuneId")
                        .HasName("pk_app_user_commune");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_app_user_commune_commune_id");

                    b.ToTable("app_user_commune", (string)null);
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChainAbsoluteExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("chain_absolute_expiry");

                    b.Property<Guid>("ChainId")
                        .HasColumnType("uuid")
                        .HasColumnName("chain_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long?>("ReplacedByTokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("SessionKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_kind");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("ChainId")
                        .HasDatabaseName("ix_refresh_token_chain_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_token_expires_at");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_token_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_token_revoked_reason", "\"revoked_reason\" IS NULL OR \"revoked_reason\" IN ('rotation', 'logout', 'reuse_detected')");

                            t.HasCheckConstraint("ck_refresh_token_session_kind", "\"session_kind\" IN ('mobile', 'web_persistent', 'web_session')");
                        });
                });

            modelBuilder.Entity("LuxMap.Modules.Survey.Entities.LuxReading", b =>
                {
                    b.Property<string>("LuxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("lux_id")
                        .HasDefaultValueSql("luxmap_format_id('LUX', nextval('lux_id_seq'), 4)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "lux_id_seq");

                    b.Property<string>("ClientOpId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_op_id");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<double>("LuxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("lux_value");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<string>("MeasuredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("measured_by");

                    b.Property<string>("MeterModel")
                        .HasColumnType("text")
                        .HasColumnName("meter_model");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pole_id");

                    b.HasKey("LuxId")
                        .HasName("pk_lux_reading");

                    b.HasIndex("ClientOpId")
                        .IsUnique()
                        .HasDatabaseName("ux_lux_reading_client_op_id");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_lux_reading_commune_id");

                    b.HasIndex("DataSource")
                        .HasDatabaseName("ix_lux_reading_data_source");

                    b.HasIndex("MeasuredBy")
                        .HasDatabaseName("ix_lux_reading_measured_by");

                    b.HasIndex("PoleId", "MeasuredAt")
                        .HasDatabaseName("ix_lux_reading_pole_id_measured_at");

                    b.ToTable("lux_reading", null, t =>
                        {
                            t.HasCheckConstraint("ck_lux_reading_data_source", "\"data_source\" IN ('field', 'public_imagery', 'calibration_rig', 'simulated')");

                            t.HasCheckConstraint("ck_lux_reading_value_non_negative", "lux_value >= 0 AND lux_value <> 'NaN'::float8 AND lux_value <> 'Infinity'::float8");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Telemetry.Entities.FeederControl", b =>
                {
                    b.Property<string>("FeederId")
                        .HasColumnType("text")
                        .HasColumnName("feeder_id");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<string>("ControlMode")
                        .HasColumnType("text")
                        .HasColumnName("control_mode");

                    b.Property<DateTime?>("ModeReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mode_reported_at");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_id");

                    b.Property<short>("RelayNo")
                        .HasColumnType("smallint")
                        .HasColumnName("relay_no");

                    b.HasKey("FeederId")
                        .HasName("pk_feeder_control");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_feeder_control_commune_id");

                    b.HasIndex("FeederId", "CommuneId")
                        .HasDatabaseName("ix_feeder_control_feeder_id_commune_id");

                    b.HasIndex("NodeId", "CommuneId")
                        .HasDatabaseName("ix_feeder_control_node_id_commune_id");

                    b.HasIndex("NodeId", "RelayNo")
                        .IsUnique()
                        .HasDatabaseName("ux_feeder_control_node_id_relay_no");

                    b.ToTable("feeder_control", null, t =>
                        {
                            t.HasCheckConstraint("ck_feeder_control_control_mode", "\"control_mode\" IS NULL OR \"control_mode\" IN ('on', 'off', 'auto')");

                            t.HasCheckConstraint("ck_feeder_control_mode_reported", "(control_mode IS NULL) = (mode_reported_at IS NULL)");

                            t.HasCheckConstraint("ck_feeder_control_relay_no_positive", "relay_no > 0");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Telemetry.Entities.IotNode", b =>
                {
                    b.Property<string>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("node_id")
                        .HasDefaultValueSql("luxmap_format_id('NODE', nextval('node_id_seq'), 3)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "node_id_seq");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("geom");

                    b.Property<DateTime?>("LastReportAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_report_at");

                    b.Property<string>("NodeRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_role");

                    b.Property<bool>("SupportsRemoteControl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_remote_control");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("NodeId")
                        .HasName("pk_iot_node");

                    b.HasAlternateKey("NodeId", "CommuneId")
                        .HasName("ak_iot_node_node_id_commune_id");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_iot_node_commune_id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_iot_node_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.ToTable("iot_node", null, t =>
                        {
                            t.HasCheckConstraint("ck_iot_node_data_source", "\"data_source\" IN ('field', 'public_imagery', 'calibration_rig', 'simulated')");

                            t.HasCheckConstraint("ck_iot_node_data_source_not_field", "data_source IN ('calibration_rig', 'simulated')");

                            t.HasCheckConstraint("ck_iot_node_node_role", "\"node_role\" IN ('segment_controller')");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.WorkOrders.Entities.WorkOrder", b =>
                {
                    b.Property<string>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("work_order_id")
                        .HasDefaultValueSql("luxmap_format_id('WO', nextval('work_order_id_seq'), 4)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "work_order_id_seq");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClusterId")
                        .HasColumnType("text")
                        .HasColumnName("cluster_id");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("MaterialsNote")
                        .HasColumnType("text")
                        .HasColumnName("materials_note");

                    b.Property<string>("MaterialsUsed")
                        .HasColumnType("text")
                        .HasColumnName("materials_used");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("ParentWorkOrderId")
                        .HasColumnType("text")
                        .HasColumnName("parent_work_order_id");

                    b.Property<string>("ReportNote")
                        .HasColumnType("text")
                        .HasColumnName("report_note");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<string>("RootWorkOrderId")
                        .HasColumnType("text")
                        .HasColumnName("root_work_order_id");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("SegmentId")
                        .HasColumnType("text")
                        .HasColumnName("segment_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("TaskKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_kind");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WoStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wo_status");

                    b.HasKey("WorkOrderId")
                        .HasName("pk_work_order");

                    b.HasAlternateKey("WorkOrderId", "CommuneId")
                        .HasName("ak_work_order_work_order_id_commune_id");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_work_order_assigned_to");

                    b.HasIndex("ClusterId")
                        .HasDatabaseName("ix_work_order_cluster_id");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_work_order_commune_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_work_order_created_by");

                    b.HasIndex("SegmentId")
                        .HasDatabaseName("ix_work_order_segment_id");

                    b.HasIndex("WoStatus")
                        .HasDatabaseName("ix_work_order_wo_status");

                    b.HasIndex("ParentWorkOrderId", "CommuneId")
                        .HasDatabaseName("ix_work_order_parent_work_order_id_commune_id");

                    b.HasIndex("RootWorkOrderId", "CommuneId")
                        .HasDatabaseName("ix_work_order_root_work_order_id_commune_id");

                    b.ToTable("work_order", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_order_assigned_at_matches", "(assigned_to IS NULL) = (assigned_at IS NULL)");

                            t.HasCheckConstraint("ck_work_order_assignee_matches_status", "(wo_status = 'open' AND assigned_to IS NULL) OR (wo_status IN ('assigned','in_progress','done','verified') AND assigned_to IS NOT NULL) OR wo_status = 'cancelled'");

                            t.HasCheckConstraint("ck_work_order_chain_complete", "(parent_work_order_id IS NULL) = (root_work_order_id IS NULL)");

                            t.HasCheckConstraint("ck_work_order_closed", "(wo_status IN ('verified','cancelled')) = (closed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_work_order_completed", "wo_status NOT IN ('done','verified') OR (completed_at IS NOT NULL AND report_note IS NOT NULL)");

                            t.HasCheckConstraint("ck_work_order_materials_note_not_blank", "materials_note IS NULL OR btrim(materials_note) <> ''");

                            t.HasCheckConstraint("ck_work_order_materials_used_not_blank", "materials_used IS NULL OR btrim(materials_used) <> ''");

                            t.HasCheckConstraint("ck_work_order_schedule_before_due", "scheduled_date IS NULL OR due_date IS NULL OR scheduled_date <= due_date");

                            t.HasCheckConstraint("ck_work_order_started", "wo_status NOT IN ('in_progress','done','verified') OR started_at IS NOT NULL");

                            t.HasCheckConstraint("ck_work_order_task_kind", "\"task_kind\" IN ('inspection', 'repair')");

                            t.HasCheckConstraint("ck_work_order_title_not_blank", "btrim(title) <> ''");

                            t.HasCheckConstraint("ck_work_order_wo_status", "\"wo_status\" IN ('open', 'assigned', 'in_progress', 'done', 'verified', 'cancelled')");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.WorkOrders.Entities.WorkOrderFault", b =>
                {
                    b.Property<string>("WorkOrderId")
                        .HasColumnType("text")
                        .HasColumnName("work_order_id");

                    b.Property<string>("FaultId")
                        .HasColumnType("text")
                        .HasColumnName("fault_id");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<string>("InspectionOutcome")
                        .HasColumnType("text")
                        .HasColumnName("inspection_outcome");

                    b.Property<DateTime>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.HasKey("WorkOrderId", "FaultId")
                        .HasName("pk_work_order_fault");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_work_order_fault_commune_id");

                    b.HasIndex("FaultId")
                        .HasDatabaseName("ix_work_order_fault_fault_id");

                    b.HasIndex("FaultId", "CommuneId")
                        .HasDatabaseName("ix_work_order_fault_fault_id_commune_id");

                    b.HasIndex("WorkOrderId", "CommuneId")
                        .HasDatabaseName("ix_work_order_fault_work_order_id_commune_id");

                    b.HasIndex(new[] { "FaultId" }, "ux_work_order_fault_fault_id_active")
                        .IsUnique()
                        .HasDatabaseName("ux_work_order_fault_fault_id_active")
                        .HasFilter("released_at IS NULL");

                    b.ToTable("work_order_fault", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_order_fault_inspection_outcome", "\"inspection_outcome\" IS NULL OR \"inspection_outcome\" IN ('fault_present', 'fault_absent', 'inconclusive')");

                            t.HasCheckConstraint("ck_work_order_fault_release_after_link", "released_at IS NULL OR released_at >= linked_at");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Persistence.AdministrativeUnit", b =>
                {
                    b.Property<string>("CommuneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("commune_id")
                        .HasDefaultValueSql("luxmap_format_id('COM', nextval('commune_id_seq'), 3)")
                        .HasAnnotation("LuxMap:PrefixedIdSequence", "commune_id_seq");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SeedKey")
                        .HasColumnType("text")
                        .HasColumnName("seed_key");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CommuneId")
                        .HasName("pk_administrative_unit");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_administrative_unit_name");

                    b.HasIndex("SeedKey")
                        .IsUnique()
                        .HasDatabaseName("ix_administrative_unit_seed_key");

                    b.ToTable("administrative_unit", (string)null);
                });

            modelBuilder.Entity("LuxMap.Persistence.Audit.AuditEvent", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_kind");

                    b.Property<string>("ActorRole")
                        .HasColumnType("text")
                        .HasColumnName("actor_role");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("text")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterState")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_state");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commune_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("AuditId")
                        .HasName("pk_audit_event");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_event_actor_user_id");

                    b.HasIndex("CommuneId")
                        .HasDatabaseName("ix_audit_event_commune_id");

                    b.HasIndex("EntityType", "EntityId", "AuditId")
                        .HasDatabaseName("ix_audit_event_entity");

                    b.ToTable("audit_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_event_action", "\"action\" IN ('created', 'assigned', 'reassigned', 'unassigned', 'started', 'completed', 'verified', 'returned', 'cancelled', 'details_changed', 'confirmed', 'rejected')");

                            t.HasCheckConstraint("ck_audit_event_actor", "(actor_kind = 'user') = (actor_user_id IS NOT NULL) AND (actor_user_id IS NULL) = (actor_role IS NULL)");

                            t.HasCheckConstraint("ck_audit_event_actor_kind", "\"actor_kind\" IN ('user', 'cv', 'iot')");

                            t.HasCheckConstraint("ck_audit_event_actor_role", "\"actor_role\" IS NULL OR \"actor_role\" IN ('superior', 'manager', 'field_engineer', 'system_admin')");

                            t.HasCheckConstraint("ck_audit_event_after_state_object", "after_state IS NULL OR jsonb_typeof(after_state) = 'object'");

                            t.HasCheckConstraint("ck_audit_event_before_state_object", "before_state IS NULL OR jsonb_typeof(before_state) = 'object'");

                            t.HasCheckConstraint("ck_audit_event_entity_type", "\"entity_type\" IN ('work_order', 'fault')");

                            t.HasCheckConstraint("ck_audit_event_has_state", "before_state IS NOT NULL OR after_state IS NOT NULL");
                        });

                    b.HasAnnotation("LuxMap:CommuneScopeApplied", true);
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Feeder", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feeder_administrative_unit_commune_id");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Fixture", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fixture_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Assets.Entities.Pole", "Pole")
                        .WithMany("Fixtures")
                        .HasForeignKey("PoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fixture_pole_pole_id");

                    b.Navigation("Pole");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Pole", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pole_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Assets.Entities.RoadSegment", "Segment")
                        .WithMany("Poles")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pole_road_segment_segment_id");

                    b.HasOne("LuxMap.Modules.Assets.Entities.Feeder", "Feeder")
                        .WithMany("Poles")
                        .HasForeignKey("FeederId", "CommuneId")
                        .HasPrincipalKey("FeederId", "CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pole_feeder_feeder_id_commune_id");

                    b.Navigation("Feeder");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.PoleCurrentStatus", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pole_current_status_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Assets.Entities.Pole", "Pole")
                        .WithOne("CurrentStatus")
                        .HasForeignKey("LuxMap.Modules.Assets.Entities.PoleCurrentStatus", "PoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pole_current_status_pole_pole_id");

                    b.Navigation("Pole");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.RoadSegment", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_road_segment_administrative_unit_commune_id");
                });

            modelBuilder.Entity("LuxMap.Modules.Faults.Entities.Fault", b =>
                {
                    b.HasOne("LuxMap.Modules.Faults.Entities.FaultCluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fault_fault_cluster_cluster_id");

                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fault_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fault_app_user_confirmed_by");

                    b.HasOne("LuxMap.Modules.Assets.Entities.Fixture", null)
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fault_fixture_fixture_id");

                    b.HasOne("LuxMap.Modules.Assets.Entities.Pole", null)
                        .WithMany()
                        .HasForeignKey("PoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fault_pole_pole_id");

                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fault_app_user_reported_by");

                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fault_app_user_resolved_by");

                    b.HasOne("LuxMap.Modules.Assets.Entities.RoadSegment", null)
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fault_road_segment_segment_id");
                });

            modelBuilder.Entity("LuxMap.Modules.Faults.Entities.FaultCluster", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fault_cluster_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Assets.Entities.RoadSegment", null)
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fault_cluster_road_segment_segment_id");
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUserCommune", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", "Commune")
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_commune_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", "User")
                        .WithMany("CommuneAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_commune_app_user_user_id");

                    b.Navigation("Commune");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("LuxMap.Modules.Identity.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_token_refresh_token_replaced_by_token_id");

                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_app_user_user_id");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuxMap.Modules.Survey.Entities.LuxReading", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lux_reading_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("MeasuredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lux_reading_app_user_measured_by");

                    b.HasOne("LuxMap.Modules.Assets.Entities.Pole", null)
                        .WithMany()
                        .HasForeignKey("PoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lux_reading_pole_pole_id");
                });

            modelBuilder.Entity("LuxMap.Modules.Telemetry.Entities.FeederControl", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feeder_control_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Assets.Entities.Feeder", null)
                        .WithMany()
                        .HasForeignKey("FeederId", "CommuneId")
                        .HasPrincipalKey("FeederId", "CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feeder_control_feeder_feeder_id_commune_id");

                    b.HasOne("LuxMap.Modules.Telemetry.Entities.IotNode", null)
                        .WithMany()
                        .HasForeignKey("NodeId", "CommuneId")
                        .HasPrincipalKey("NodeId", "CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feeder_control_iot_node_node_id_commune_id");
                });

            modelBuilder.Entity("LuxMap.Modules.Telemetry.Entities.IotNode", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_iot_node_administrative_unit_commune_id");
                });

            modelBuilder.Entity("LuxMap.Modules.WorkOrders.Entities.WorkOrder", b =>
                {
                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_order_app_user_assigned_to");

                    b.HasOne("LuxMap.Modules.Faults.Entities.FaultCluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_order_fault_cluster_cluster_id");

                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_order_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_order_app_user_created_by");

                    b.HasOne("LuxMap.Modules.Assets.Entities.RoadSegment", null)
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_order_road_segment_segment_id");

                    b.HasOne("LuxMap.Modules.WorkOrders.Entities.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("ParentWorkOrderId", "CommuneId")
                        .HasPrincipalKey("WorkOrderId", "CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_order_work_order_parent_work_order_id_commune_id");

                    b.HasOne("LuxMap.Modules.WorkOrders.Entities.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("RootWorkOrderId", "CommuneId")
                        .HasPrincipalKey("WorkOrderId", "CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_order_work_order_root_work_order_id_commune_id");
                });

            modelBuilder.Entity("LuxMap.Modules.WorkOrders.Entities.WorkOrderFault", b =>
                {
                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_order_fault_administrative_unit_commune_id");

                    b.HasOne("LuxMap.Modules.Faults.Entities.Fault", null)
                        .WithMany()
                        .HasForeignKey("FaultId", "CommuneId")
                        .HasPrincipalKey("FaultId", "CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_order_fault_fault_fault_id_commune_id");

                    b.HasOne("LuxMap.Modules.WorkOrders.Entities.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderId", "CommuneId")
                        .HasPrincipalKey("WorkOrderId", "CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_order_fault_work_order_work_order_id_commune_id");
                });

            modelBuilder.Entity("LuxMap.Persistence.Audit.AuditEvent", b =>
                {
                    b.HasOne("LuxMap.Modules.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_event_app_user_actor_user_id");

                    b.HasOne("LuxMap.Persistence.AdministrativeUnit", null)
                        .WithMany()
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_event_administrative_unit_commune_id");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Feeder", b =>
                {
                    b.Navigation("Poles");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.Pole", b =>
                {
                    b.Navigation("CurrentStatus");

                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("LuxMap.Modules.Assets.Entities.RoadSegment", b =>
                {
                    b.Navigation("Poles");
                });

            modelBuilder.Entity("LuxMap.Modules.Identity.Entities.AppUser", b =>
                {
                    b.Navigation("CommuneAssignments");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
