using LuxMap.Persistence.Conventions;
using LuxMap.Shared.Contracts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LuxMap.Persistence;

/// <summary>
/// A commune-level administrative unit. Its ID looks like <c>COM-001</c> (Contract section 0.2); it
/// is the value every <c>commune_id</c> column points at, and the unit of territorial authorization
/// (Contract section 7).
/// </summary>
/// <remarks>
/// <b>It lives in Persistence, not in the Identity module.</b> It is not an Identity concept — it is
/// the anchor that 15 of the 16 entities scope against, and Persistence already owns the machinery
/// that enforces that scoping: <c>ICommuneScoped</c>, <c>HasCommuneScope()</c>, <c>HasCommuneReference()</c>
/// and the startup guard. Putting the anchor table beside the mechanism means every module can point
/// a real foreign key at it through the Persistence reference they all already have, instead of
/// depending on Identity.
/// <para>
/// ⚠️ It deliberately does NOT implement <c>ICommuneScoped</c>. It is the anchor, not a resource
/// being filtered; putting the global filter on the anchor table itself would be circular — the row
/// defining a commune would be hidden by the scope derived from it. Endpoints that list communes
/// query the <c>commune_ids</c> claim explicitly. Do not "fix" this for consistency.
/// </para>
/// <para>
/// No boundary polygon column: section 7 compares the claim against the <c>commune_id</c> column
/// rather than doing spatial containment, and Branch C has no source of real boundaries. Adding a
/// nullable column later is one small migration.
/// </para>
/// </remarks>
public class AdministrativeUnit
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string CommuneId { get; set; } = null!;

    public required string Name { get; set; }

    /// <summary>
    /// A stable key naming the ROLE this unit plays in the study, for seeding. <c>NULL</c> for
    /// communes created later by a user.
    /// </summary>
    /// <remarks>
    /// Seeding used to be idempotent on <see cref="Name"/>, which is the one field certain to change:
    /// BE-06 seeds the placeholder "Commune 01" and BE-39 sets the real name, at which point a
    /// name-keyed upsert creates a SECOND row instead of renaming the first. Keying on the role
    /// instead makes renaming free.
    /// <para>
    /// Not an official administrative code: the study sites have not been chosen, so a real code
    /// would have to be invented. The role each row plays IS known, and that is what this records.
    /// See <see cref="SeedKeys"/>.
    /// </para>
    /// </remarks>
    public string? SeedKey { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}

/// <summary>The <see cref="AdministrativeUnit.SeedKey"/> values this project defines.</summary>
public static class SeedKeys
{
    /// <summary>The commune whose lighting is under study — the poles in the FO-26 mock set.</summary>
    public const string StudySite = "study_site";

    /// <summary>
    /// The commune housing the FO-07 calibration rig. A SEPARATE unit on purpose: Contract section
    /// 2.9 registers the rig as ordinary assets, and keeping it in another commune means BE-08's
    /// query filter keeps calibration data out of the study commune's statistics even if someone
    /// forgets to filter on <c>data_source</c>. Two independent layers rather than one.
    /// </summary>
    public const string CalibrationSite = "calibration_site";
}

public sealed class AdministrativeUnitConfiguration : IEntityTypeConfiguration<AdministrativeUnit>
{
    public void Configure(EntityTypeBuilder<AdministrativeUnit> builder)
    {
        builder.ToTable(CommuneReferenceBuilderExtensions.CommuneTable);
        builder.HasKey(unit => unit.CommuneId);

        builder.Property(unit => unit.CommuneId).HasPrefixedId(PrefixedIds.AdministrativeUnit);
        builder.Property(unit => unit.Name).HasColumnType("text").IsRequired();
        builder.Property(unit => unit.SeedKey).HasColumnType("text");
        builder.Property(unit => unit.CreatedAt).HasDefaultValueSql("now()");
        builder.Property(unit => unit.UpdatedAt).HasDefaultValueSql("now()");

        builder.HasIndex(unit => unit.Name).IsUnique();

        // Unique but nullable: PostgreSQL allows any number of NULLs in a unique index, so communes
        // created by a user need no key while the seeded ones stay exactly one row each.
        builder.HasIndex(unit => unit.SeedKey).IsUnique();
    }
}
