namespace LuxMap.Modules.Identity.Entities;

/// <summary>
/// A commune-level administrative unit. Its ID looks like <c>COM-001</c> (Contract section 0.2); it
/// is the value that <c>commune_id</c> on Pole, Fault and friends points at, and the unit of
/// territorial authorization (section 7).
/// </summary>
/// <remarks>
/// No boundary polygon column yet: section 7 authorization compares the <c>commune_ids</c> claim
/// against the <c>commune_id</c> column rather than doing spatial containment, and Branch C has no
/// source of real boundaries. Adding a nullable column later is one small migration.
/// </remarks>
public class AdministrativeUnit
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string CommuneId { get; set; } = null!;

    public required string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public ICollection<AppUserCommune> UserAssignments { get; set; } = [];
}
