using LuxMap.Shared.Contracts.Enums;

namespace LuxMap.Modules.Identity.Entities;

/// <summary>
/// A user account. Its ID looks like <c>USR-001</c> (Contract section 0.2).
/// There is no Citizen role — see <see cref="UserRole"/>.
/// </summary>
public class AppUser
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string UserId { get; set; } = null!;

    public required string Username { get; set; }

    public required string Email { get; set; }

    public required string FullName { get; set; }

    /// <summary>
    /// The encoded <c>PasswordHasher</c> string. The salt is embedded inside it, which is why there
    /// is no separate salt column. BE-07 implements hashing and verification; BE-06 only builds the
    /// schema.
    /// </summary>
    public required string PasswordHash { get; set; }

    /// <summary>
    /// Which algorithm produced the hash, e.g. <c>pbkdf2-aspnetcore-v3</c>. Having this column means
    /// changing algorithms later needs no schema change, and identifies rows that need rehashing.
    /// </summary>
    public required string PasswordAlgorithm { get; set; }

    public UserRole Role { get; set; }

    /// <summary>Locks the account: blocks sign-in while preserving the user's history.</summary>
    public bool IsLocked { get; set; }

    /// <summary>
    /// Contract section 7: administrators have system-wide scope and their claim carries the special
    /// value <c>*</c>. A flag rather than every commune in the join table, so adding a commune
    /// requires no change here.
    /// </summary>
    public bool HasSystemWideScope { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public ICollection<AppUserCommune> CommuneAssignments { get; set; } = [];

    public ICollection<RefreshToken> RefreshTokens { get; set; } = [];
}

/// <summary>
/// The user-to-commune join table backing the <c>commune_ids</c> claim of Contract section 7.
/// Many-to-many because a managing authority can cover several communes.
/// </summary>
public class AppUserCommune
{
    public required string UserId { get; set; }

    public required string CommuneId { get; set; }

    public DateTime AssignedAt { get; set; }

    public AppUser User { get; set; } = null!;

    public AdministrativeUnit Commune { get; set; } = null!;
}
