using LuxMap.Shared.Authorization;
using LuxMap.Shared.Contracts.Enums;
using NetTopologySuite.Geometries;

namespace LuxMap.Modules.Assets.Entities;

/// <summary>
/// A main electrical cabinet (trụ / tủ điện tổng) feeding one or more circuits. Its ID looks like
/// <c>CAB-001</c> (drift CABINET, CAB-1 — SELF-SIGNED, not yet in the Contract).
/// </summary>
/// <remarks>
/// <para>
/// <b>An asset, not a device.</b> Every circuit leaves from a cabinet and the cabinet stands whether or
/// not anything is installed in it; an IoT device is fitted only where the commune asks for one. The same
/// split as <see cref="Pole"/> and <see cref="Fixture"/>: the location belongs to the structure, the
/// device is replaceable equipment mounted on it. Until this table existed the cabinet's position lived on
/// <c>iot_node.geom</c>, so a cabinet without a device had nowhere to be recorded.
/// </para>
/// <para>
/// Chain: cabinet → <see cref="Feeder"/> (<c>feeder.cabinet_id</c>) → <c>pole.feeder_id</c>, and
/// cabinet → <c>iot_node</c> → <c>feeder_control</c> (relay) → feeder.
/// </para>
/// </remarks>
public class ElectricalCabinet : ICommuneScoped, IExternallyReferenced, IUpdateStamped
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string CabinetId { get; set; } = null!;

    public required string CabinetName { get; set; }

    /// <summary>The authority's own code, e.g. the number painted on the cabinet. Same rules as on <see cref="Feeder"/>.</summary>
    public string? ExternalRef { get; set; }

    public required string CommuneId { get; set; }

    /// <summary>
    /// <c>geometry(Point, 4326)</c>, REQUIRED (CAB-1). A cabinet is something a surveyor can stand next
    /// to and photograph — unlike a cable route, there is no honest reason not to know where it is.
    /// </summary>
    public required Point Geom { get; set; }

    /// <summary>
    /// Field cabinets and the testbed cabinet must stay apart all the way to the statistics. A device may
    /// sit only on a cabinet that is NOT <c>field</c> (CAB-5, D-R10).
    /// </summary>
    public DataSource DataSource { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string? UpdatedBy { get; set; }
}
