using LuxMap.Shared.Authorization;
using NetTopologySuite.Geometries;

namespace LuxMap.Modules.Assets.Entities;

/// <summary>
/// An electrical circuit feeding a group of poles. Its ID looks like <c>FDR-001</c> (Contract
/// section 0.2).
/// <para>
/// Feeder is what makes CV-15 possible: a breaker trip or a broken conductor propagates along the
/// CIRCUIT, not along the road. Being able to ask "every pole on feeder X" (BE-13) is what turns a
/// scatter of dark poles into ONE <c>segment_outage</c> cause rather than N lamp faults.
/// </para>
/// </summary>
/// <remarks>
/// The Contract specifies exactly one thing about Feeder: the <c>FDR</c> prefix. It appears in no
/// mock and in no endpoint. Everything here beyond id and geometry comes from the task list
/// (BE-03 "LineString for roads AND feeders", BE-13 "assign poles to a feeder") and was confirmed
/// before implementation — no business fields were invented.
/// <para>
/// There is deliberately NO relationship to <see cref="RoadSegment"/>: road geography and electrical
/// topology are independent, and they meet through <see cref="Pole"/>.
/// </para>
/// </remarks>
public class Feeder : ICommuneScoped, IExternallyReferenced
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string FeederId { get; set; } = null!;

    /// <summary>Required: BE-13 shows it when assigning poles, so an unnamed circuit is unusable.</summary>
    public required string FeederName { get; set; }

    /// <summary>
    /// The owning authority's own inventory code — the number painted on the cabinet, or the
    /// reference in the FO-10 spreadsheet. <c>NULL</c> is allowed and meaningful: assets traced from
    /// public night imagery carry no inventory code at all.
    /// </summary>
    /// <remarks>
    /// This is the schema's ONLY natural key, and it is what makes CSV import idempotent. Without it
    /// nothing links <c>CTA-001</c> in this month's file to the row created from last month's, so
    /// re-running the same file duplicates every asset. Uniqueness is
    /// <c>(commune_id, external_ref) WHERE external_ref IS NOT NULL</c> — a PARTIAL index, so any
    /// number of code-less rows may coexist in one commune.
    /// <para>
    /// <b>Stored and searchable, never emitted.</b> The Contract publishes no such field, and adding
    /// one to a response would change a shape the front end has already built against. Same treatment
    /// as <c>data_source</c> at the asset layer.
    /// </para>
    /// </remarks>
    public string? ExternalRef { get; set; }

    public required string CommuneId { get; set; }

    /// <summary>
    /// <c>geometry(LineString, 4326)</c>, NULLABLE — unlike every other geometry column here.
    /// <para>
    /// Branch C has no field survey (FO-01), so the real cable route is almost certainly unmeasured.
    /// Requiring it would force someone to invent a route. The GIST index still applies: PostgreSQL
    /// simply does not index the NULL rows.
    /// </para>
    /// </summary>
    public LineString? Geom { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public ICollection<Pole> Poles { get; set; } = [];
}
