using LuxMap.Shared.Authorization;
using LuxMap.Shared.Contracts.Enums;

namespace LuxMap.Modules.Assets.Entities;

/// <summary>
/// A lamp mounted on a pole. Its ID looks like <c>FIX-0001</c> (Contract section 0.2).
/// <para>
/// This entity records an INSTALLATION: which device, on which pole, from when to when. Replacing a
/// lamp sets <see cref="RemovedDate"/> on the old row and inserts a new one, so the pole keeps its
/// full equipment history.
/// </para>
/// </summary>
/// <remarks>
/// ⚠️ There is deliberately NO status column here. Status belongs to the pole POSITION
/// (<see cref="PoleCurrentStatus"/>), for two reasons that both have teeth:
/// <list type="number">
/// <item>CV cannot observe it per fixture. Detection reads night imagery: the camera sees one light
/// source at one position and measures its luminance against that position's own baseline. It cannot
/// tell lamp #1 from lamp #2 on the same pole.</item>
/// <item>Per-fixture status would force an aggregation rule, and no correct one exists. Two fixtures,
/// one <c>out</c> and one <c>unknown</c>, would require ranking <c>unknown</c> against <c>out</c> on
/// a severity ladder — and Contract section 1 forbids exactly that: <c>unknown</c> is not a fault and
/// must never be folded into <c>out</c>. The model that avoids the question is the correct one.</item>
/// </list>
/// </remarks>
public class Fixture : ICommuneScoped
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string FixtureId { get; set; } = null!;

    public required string PoleId { get; set; }

    /// <summary>
    /// Denormalized from <see cref="Pole"/> so this entity can implement <see cref="ICommuneScoped"/>
    /// and be protected by the model-building guard rather than by remembering to join.
    /// </summary>
    /// <remarks>
    /// A fixture always sits in the commune of the pole carrying it, and moving one to a pole in
    /// another commune is in practice a new installation record — so the copy cannot realistically
    /// drift. Fixture is never returned as a resource of its own (Contract section 2.1 flattens it
    /// into the pole's properties), so the extra column breaks no published shape.
    /// </remarks>
    public required string CommuneId { get; set; }

    public FixtureType FixtureType { get; set; }

    public PowerSource PowerSource { get; set; }

    public int LampWatt { get; set; }

    /// <summary>
    /// <c>date</c>, not <c>timestamptz</c> — Contract section 0 separates the two, and a fitting is
    /// installed on a day, not at an instant.
    /// </summary>
    public DateOnly InstallDate { get; set; }

    /// <summary>
    /// When this fixture was taken off the pole. <c>NULL</c> means it is the one currently in service;
    /// that is what the partial index keys on and what BE-14 flattens into the pole's properties.
    /// </summary>
    public DateOnly? RemovedDate { get; set; }

    /// <summary>Nullable: not every fitting comes with a warranty on record.</summary>
    public DateOnly? WarrantyExpiry { get; set; }

    /// <summary>See <see cref="Pole.DataSource"/> — the FO-07 rig's lamps carry <c>calibration_rig</c>.</summary>
    public DataSource DataSource { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public Pole Pole { get; set; } = null!;
}
