using LuxMap.Shared.Authorization;
using LuxMap.Shared.Contracts.Enums;
using NetTopologySuite.Geometries;

namespace LuxMap.Modules.Assets.Entities;

/// <summary>
/// A lighting pole — the PHYSICAL STRUCTURE. Its ID looks like <c>POLE-0001</c> (Contract section 0.2).
/// <para>
/// <see cref="Pole"/> and <see cref="Fixture"/> are two tables on purpose (BE-09). The pole is the
/// structure; the fixture is the device bolted onto it. A fixture can be replaced while the pole
/// stands, and status history belongs to the POLE POSITION — which is why status lives in
/// <see cref="PoleCurrentStatus"/>, keyed by pole, and not on the fixture.
/// </para>
/// </summary>
/// <remarks>
/// Of the fifteen properties Contract section 2.1 returns, this table stores only what is genuinely
/// an attribute of the structure. The rest are assembled by BE-14:
/// <list type="bullet">
/// <item><c>fixture_type</c>, <c>power_source</c>, <c>lamp_watt</c>, <c>install_date</c>,
/// <c>warranty_expiry</c> — flattened from the ACTIVE <see cref="Fixture"/>.</item>
/// <item><c>fixture_status</c>, <c>status_confidence</c>, <c>last_seen_at</c>, <c>last_sweep_id</c>
/// — from <see cref="PoleCurrentStatus"/>.</item>
/// <item><c>open_fault_count</c>, <c>has_iot_node</c> — computed at query time. At this project's
/// scale those are a hash aggregate and a semi-join over a few thousand rows; storing them would buy
/// no measurable speed and would cost a fact kept in two places.</item>
/// </list>
/// </remarks>
public class Pole : ICommuneScoped
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string PoleId { get; set; } = null!;

    public required string SegmentId { get; set; }

    /// <summary>
    /// The electrical circuit feeding this pole. NULLABLE, and that is load-bearing: a
    /// <c>solar_all_in_one</c> pole is connected to no circuit at all. Sparse IoT and off-grid solar
    /// are the design, not gaps to be filled in.
    /// </summary>
    public string? FeederId { get; set; }

    public required string CommuneId { get; set; }

    /// <summary>
    /// <c>geometry(Point, 4326)</c>, always WGS84. EPSG:3405 is internal to distance calculations
    /// (BE-10) and never reaches the API. Backed by the GIST index the <c>bbox</c> queries need.
    /// </summary>
    public required Point Geom { get; set; }

    /// <summary>
    /// Near a school, market, bridge or junction — raises repair priority, and the front end draws a
    /// secondary icon for it.
    /// </summary>
    /// <remarks>
    /// This is NOT a derived field, despite sitting among the derived ones in section 2.1: the domain
    /// model has no POI entity and Branch C has no POI source, so there is nothing to join against.
    /// An operator sets it, exactly like <c>lamp_watt</c>.
    /// </remarks>
    public bool NearSensitivePoi { get; set; }

    /// <summary>
    /// Which of Branch C's three data sources this pole belongs to. Contract section 2.9 registers
    /// the FO-07 calibration rig as ordinary poles on an ordinary segment so the pipeline never
    /// branches; this column is what keeps rig poles separable in every statistic afterwards.
    /// Stored and filterable, NOT emitted in <c>properties</c>.
    /// </summary>
    public DataSource DataSource { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public RoadSegment Segment { get; set; } = null!;

    public Feeder? Feeder { get; set; }

    public ICollection<Fixture> Fixtures { get; set; } = [];

    /// <summary>Absent until a sweep has classified this pole — see <see cref="PoleCurrentStatus"/>.</summary>
    public PoleCurrentStatus? CurrentStatus { get; set; }
}
