using LuxMap.Shared.Authorization;
using LuxMap.Shared.Contracts.Enums;
using NetTopologySuite.Geometries;

namespace LuxMap.Modules.Assets.Entities;

/// <summary>
/// A stretch of road carrying poles. Its ID looks like <c>SEG-001</c> (Contract section 0.2).
/// <para>
/// A road segment is ROAD geography; <see cref="Feeder"/> is the ELECTRICAL circuit. They are
/// deliberately separate: one feeder powers poles spread over several segments, and one long segment
/// can be fed by two circuits. That is the whole reason both types exist — see <see cref="Pole"/>,
/// which is where the two meet.
/// </para>
/// </summary>
/// <remarks>
/// Three of the seven properties Contract section 2.3 returns are NOT columns here, because they are
/// derived and storing them would put the same fact in two places:
/// <list type="bullet">
/// <item><c>pole_count</c> — <c>COUNT(pole WHERE segment_id = ...)</c>.</item>
/// <item><c>controller_node_id</c> — the relationship is owned by <c>IotNode</c>, which carries
/// <c>segment_id</c> and <c>node_role</c> (see <c>mock-iot-nodes.geojson</c>). IOT-10 owns it.</item>
/// <item><c>has_active_segment_fault</c> — output of the CV-15 clustering, derived from Fault (BE-18).</item>
/// </list>
/// BE-14 computes all three when it builds the FeatureCollection.
/// </remarks>
public class RoadSegment : ICommuneScoped, IExternallyReferenced
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string SegmentId { get; set; } = null!;

    public required string SegmentName { get; set; }

    /// <summary>
    /// The owning authority's own inventory code — the number painted on the segment marker, or the
    /// reference in the FO-10 spreadsheet. <c>NULL</c> is allowed and meaningful: assets traced from
    /// public night imagery carry no inventory code at all.
    /// </summary>
    /// <remarks>
    /// This is the schema's ONLY natural key, and it is what makes CSV import idempotent. Without it
    /// nothing links <c>CTA-001</c> in this month's file to the row created from last month's, so
    /// re-running the same file duplicates every asset. Uniqueness is
    /// <c>(commune_id, external_ref) WHERE external_ref IS NOT NULL</c> — a PARTIAL index, so any
    /// number of code-less rows may coexist in one commune.
    /// <para>
    /// <b>Stored and searchable, never emitted.</b> The Contract publishes no such field, and adding
    /// one to a response would change a shape the front end has already built against. Same treatment
    /// as <c>data_source</c> at the asset layer.
    /// </para>
    /// </remarks>
    public string? ExternalRef { get; set; }

    public RoadClass RoadClass { get; set; }

    /// <summary>
    /// Length in metres, STORED rather than derived. It is a published property of section 2.3, and
    /// recomputing <c>ST_Length</c> on every bbox request would be wasted work; the mock values agree
    /// with the geometry to within a metre. BE-10 owns the distance convention that keeps it honest.
    /// </summary>
    public int LengthM { get; set; }

    /// <summary>
    /// <c>geometry(LineString, 4326)</c>. Required: a segment with no route cannot be drawn, and the
    /// GIST index exists to serve exactly this column.
    /// </summary>
    public required LineString Geom { get; set; }

    /// <summary>
    /// The commune administering this segment.
    /// </summary>
    /// <remarks>
    /// ⚠️ <c>road_class = inter_commune</c> literally means a road running BETWEEN communes, so a
    /// single owning commune is a simplification. It does not surface while the data covers one
    /// commune; a second commune of road makes this a many-to-many. Recorded for FW-00.
    /// <para>
    /// The column exists to drive the section 7 filter and the <c>commune_id</c> query parameter of
    /// section 2.3. It is NOT emitted in <c>properties</c> — <c>mock-segments.geojson</c> is the
    /// source of truth for the response shape and does not carry it.
    /// </para>
    /// </remarks>
    public required string CommuneId { get; set; }

    /// <summary>
    /// Which of Branch C's three data sources this segment belongs to. Lets the FO-07 calibration rig
    /// be registered as a real segment (Contract section 2.9) while staying separable in every
    /// statistic (BE-28, BE-30). Stored and filterable, NOT emitted in <c>properties</c>.
    /// </summary>
    public DataSource DataSource { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public ICollection<Pole> Poles { get; set; } = [];
}
