using LuxMap.Shared.Authorization;
using LuxMap.Shared.Contracts.Enums;
using NetTopologySuite.Geometries;

namespace LuxMap.Modules.Telemetry.Entities;

/// <summary>
/// An IoT device in a main lighting cabinet (drift "BE-14 / IoT", I-1…I-6).
/// </summary>
/// <remarks>
/// <para>
/// There is NO device on individual poles (I-1): the only role left is
/// <see cref="NodeRole.SegmentController"/>, kept under that name so the front end does not change
/// (I-7). The device sits at the cabinet, so it has its own point (I-4) and reaches lamps through
/// the feeders it switches — <see cref="FeederControl"/> — never through a pole column.
/// </para>
/// <para>
/// <c>node_status</c> is NOT stored (I-3). It is derived on read from <see cref="LastReportAt"/> and
/// <see cref="IotOptions.OfflineAfter"/>; a stored status would need a job to flip it to offline,
/// because a dead device cannot report its own death.
/// </para>
/// </remarks>
public class IotNode : ICommuneScoped
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string NodeId { get; set; } = null!;

    public required string CommuneId { get; set; }

    public NodeRole NodeRole { get; set; } = NodeRole.SegmentController;

    /// <summary>The cabinet's location, EPSG:4326.</summary>
    public required Point Geom { get; set; }

    /// <summary>
    /// <c>true</c> only for the self-built testbed (D-R7): the team never operates a commune's grid,
    /// so a device in the field only measures and reports.
    /// </summary>
    public bool SupportsRemoteControl { get; set; }

    /// <summary>
    /// <c>calibration_rig</c> for the testbed hardware (I-5), <c>simulated</c> for demo rows. Never
    /// <c>field</c>: the team installs nothing in the field (D-R10).
    /// </summary>
    public DataSource DataSource { get; set; }

    /// <summary>Written by telemetry ingest (IOT-09). NULL means the device has never reported.</summary>
    public DateTime? LastReportAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}
