using System.Security.Claims;
using System.Text.Json;
using LuxMap.Modules.Identity.Auth;
using LuxMap.Modules.Identity.Entities;
using LuxMap.Modules.Identity.Seeding;
using LuxMap.Persistence;
using LuxMap.Persistence.Audit;
using LuxMap.Shared.Contracts.Enums;
using LuxMap.Shared.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Npgsql;

namespace LuxMap.Api.Tests;

[Collection(nameof(AssetDatabaseCollection))]
public class AuditTrailTests(AssetSchemaFixture fixture) : IAsyncLifetime
{
    private readonly string correlationId = $"BE-23a-{Guid.NewGuid():N}";

    public Task InitializeAsync()
    {
        SignIn(fixture.CommuneId);
        return Task.CompletedTask;
    }

    public async Task DisposeAsync()
    {
        fixture.Services.GetRequiredService<IHttpContextAccessor>().HttpContext = null;
        await fixture.QueryAsync(async db =>
        {
            await using var transaction = await db.Database.BeginTransactionAsync();
            await db.Database.ExecuteSqlRawAsync("SET LOCAL luxmap.audit_purge = 'on'");
            await db.Database.ExecuteSqlInterpolatedAsync(
                $"DELETE FROM audit_event WHERE correlation_id = {correlationId}");
            await transaction.CommitAsync();
            return 0;
        });
    }

    [Fact]
    public async Task User_event_round_trips_every_column()
    {
        var username = $"audit-{Guid.NewGuid():N}"[..20];
        var user = new AppUser
        {
            Username = username, Email = $"{username}@luxmap.local", FullName = "Audit throwaway actor",
            PasswordHash = string.Empty, PasswordAlgorithm = IdentitySeeder.PasswordAlgorithm,
            Role = UserRole.Manager,
        };
        try
        {
            await fixture.QueryAsync(async db =>
            {
                db.Add(user);
                await db.SaveChangesAsync();
                Writer(db).Record(new AuditChange(
                    new DateTime(2026, 9, 28, 1, 2, 3, DateTimeKind.Utc),
                    AuditActorKind.User, user.UserId, UserRole.Manager, fixture.CommuneId,
                    AuditEntityType.WorkOrder, "WO-0042", AuditAction.Reassigned,
                    new { WoStatus = WorkOrderStatus.Open }, new { WoStatus = WorkOrderStatus.Assigned },
                    "Assigned to the replacement engineer"));
                return await db.SaveChangesAsync();
            });

            await fixture.QueryAsync(async db =>
            {
                var audit = await db.Set<AuditEvent>().SingleAsync(a => a.CorrelationId == correlationId);
                Assert.True(audit.AuditId > 0);
                Assert.Equal(new DateTime(2026, 9, 28, 1, 2, 3, DateTimeKind.Utc), audit.OccurredAt);
                Assert.Equal(AuditActorKind.User, audit.ActorKind);
                // These IDs are generated by the DB, never fixed to seed accounts/communes.
                Assert.Equal(user.UserId, audit.ActorUserId);
                Assert.Equal(UserRole.Manager, audit.ActorRole);
                Assert.Equal(fixture.CommuneId, audit.CommuneId);
                Assert.Equal(AuditEntityType.WorkOrder, audit.EntityType);
                Assert.Equal("WO-0042", audit.EntityId);
                Assert.Equal(AuditAction.Reassigned, audit.Action);
                Assert.Equal("{\"wo_status\": \"open\"}", audit.BeforeState);
                Assert.Equal("{\"wo_status\": \"assigned\"}", audit.AfterState);
                Assert.Equal("Assigned to the replacement engineer", audit.Note);
                Assert.Equal(correlationId, audit.CorrelationId);
                return 0;
            });
        }
        finally
        {
            await fixture.QueryAsync(async db =>
            {
                await using (var transaction = await db.Database.BeginTransactionAsync())
                {
                    await db.Database.ExecuteSqlRawAsync("SET LOCAL luxmap.audit_purge = 'on'");
                    await db.Database.ExecuteSqlInterpolatedAsync(
                        $"DELETE FROM audit_event WHERE correlation_id = {correlationId}");
                    await transaction.CommitAsync();
                }
                return await db.Database.ExecuteSqlInterpolatedAsync(
                    $"DELETE FROM app_user WHERE username = {username}");
            });
        }
    }

    [Fact]
    public async Task Record_stages_one_event_with_business_timestamp_and_contract_json()
    {
        var now = DateTime.UtcNow;
        await using (var scope = fixture.Services.CreateAsyncScope())
        {
            // Ensure the registered scoped writer and caller share exactly the same DbContext.
            var db = scope.ServiceProvider.GetRequiredService<LuxMapDbContext>();
            var holder = scope.ServiceProvider.GetRequiredService<LuxMap.Api.Http.CorrelationIdHolder>();
            holder.CorrelationId = correlationId;
            var writer = scope.ServiceProvider.GetRequiredService<IAuditTrail>();
            writer.Record(Change(now));
            Assert.Single(db.ChangeTracker.Entries<AuditEvent>());
            Assert.Equal(0, await CountAsync());
            await db.SaveChangesAsync();
        }

        await fixture.QueryAsync(async db =>
        {
            var audit = await db.Set<AuditEvent>().SingleAsync(a => a.CorrelationId == correlationId);
            Assert.True(audit.AuditId > 0);
            // PostgreSQL stores microseconds, not .NET ticks.
            Assert.InRange((audit.OccurredAt - now).Duration().Ticks, 0, 9);
            Assert.Null(audit.ActorUserId);
            Assert.Null(audit.ActorRole);
            Assert.Equal(AuditActorKind.Cv, audit.ActorKind);
            using var state = JsonDocument.Parse(audit.AfterState!);
            Assert.Equal("in_progress", state.RootElement.GetProperty("wo_status").GetString());
            Assert.EndsWith("Z", state.RootElement.GetProperty("observed_at").GetString(), StringComparison.Ordinal);
            return 0;
        });
        Assert.Equal(1, await CountAsync());
    }

    [Fact]
    public async Task Business_write_and_audit_rollback_together()
    {
        var name = $"audit-rollback-{Guid.NewGuid():N}";
        await fixture.QueryAsync(async db =>
        {
            await using var transaction = await db.Database.BeginTransactionAsync();
            db.Add(new AdministrativeUnit { Name = name });
            Writer(db).Record(Change(DateTime.UtcNow));
            Assert.Equal(2, await db.SaveChangesAsync());
            Assert.Equal(1, await db.Set<AuditEvent>().CountAsync(a => a.CorrelationId == correlationId));
            await transaction.RollbackAsync();
            return 0;
        });
        Assert.Equal(0, await CountAsync());
        Assert.False(await fixture.QueryAsync(db => db.Set<AdministrativeUnit>().AnyAsync(a => a.Name == name)));
    }

    [Fact]
    public async Task Invalid_audit_rolls_back_business_write_in_the_same_save()
    {
        var name = $"audit-failed-{Guid.NewGuid():N}";
        var failure = await Assert.ThrowsAsync<DbUpdateException>(() => fixture.QueryAsync(async db =>
        {
            db.Add(new AdministrativeUnit { Name = name });
            Writer(db).Record(Change(DateTime.UtcNow) with { AfterState = null });
            return await db.SaveChangesAsync();
        }));
        Assert.Equal("ck_audit_event_has_state", Assert.IsType<PostgresException>(failure.InnerException).ConstraintName);
        Assert.Equal(0, await CountAsync());
        Assert.False(await fixture.QueryAsync(db => db.Set<AdministrativeUnit>().AnyAsync(a => a.Name == name)));
    }

    [Theory]
    [InlineData("UPDATE")]
    [InlineData("DELETE")]
    [InlineData("TRUNCATE")]
    public async Task Raw_sql_cannot_mutate_audit(string operation)
    {
        await InsertAsync();
        var failure = await Assert.ThrowsAsync<PostgresException>(() => fixture.QueryAsync(async db =>
        {
            // Explicit transaction ensures even the deliberately sabotaged TRUNCATE is rolled back.
            await using var transaction = await db.Database.BeginTransactionAsync();
            return operation switch
            {
                "UPDATE" => await db.Database.ExecuteSqlInterpolatedAsync(
                    $"UPDATE audit_event SET note = 'tampered' WHERE correlation_id = {correlationId}"),
                "DELETE" => await db.Database.ExecuteSqlInterpolatedAsync(
                    $"DELETE FROM audit_event WHERE correlation_id = {correlationId}"),
                _ => await db.Database.ExecuteSqlRawAsync("TRUNCATE audit_event"),
            };
        }));
        Assert.Equal("55000", failure.SqlState);
        Assert.Contains("append-only", failure.MessageText, StringComparison.Ordinal);
        Assert.Equal(1, await CountAsync());
    }

    [Fact]
    public async Task Teardown_switch_is_local_to_its_transaction()
    {
        await InsertAsync();
        await fixture.QueryAsync(async db =>
        {
            await db.Database.OpenConnectionAsync();
            await using (var transaction = await db.Database.BeginTransactionAsync())
            {
                await db.Database.ExecuteSqlRawAsync("SET LOCAL luxmap.audit_purge = 'on'");
                Assert.Equal(1, await db.Database.ExecuteSqlInterpolatedAsync(
                    $"DELETE FROM audit_event WHERE correlation_id = {correlationId}"));
                await transaction.RollbackAsync();
            }
            var failure = await Assert.ThrowsAsync<PostgresException>(() => db.Database.ExecuteSqlInterpolatedAsync(
                $"DELETE FROM audit_event WHERE correlation_id = {correlationId}"));
            Assert.Equal("55000", failure.SqlState);
            return 0;
        });
        Assert.Equal(1, await CountAsync());
    }

    [Fact]
    public async Task Audit_read_and_write_are_commune_scoped()
    {
        await InsertAsync();
        SignIn();
        Assert.Equal(0, await fixture.QueryAsync(db => db.Set<AuditEvent>().CountAsync(a => a.CorrelationId == correlationId)));
        var error = await Assert.ThrowsAsync<LuxMapException>(() => InsertAsync());
        Assert.Equal("COMMUNE_FORBIDDEN", error.Code);
        Assert.Equal(1, await CountAsync());
    }

    [Theory]
    [InlineData(AuditActorKind.User, null, null)]
    [InlineData(AuditActorKind.Cv, "USR-001", UserRole.SystemAdmin)]
    [InlineData(AuditActorKind.Iot, null, UserRole.Manager)]
    public async Task Database_rejects_inconsistent_actor(AuditActorKind kind, string? userId, UserRole? role)
    {
        var error = await Assert.ThrowsAsync<DbUpdateException>(() => fixture.QueryAsync(async db =>
        {
            Writer(db).Record(Change(DateTime.UtcNow) with { ActorKind = kind, ActorUserId = userId, ActorRole = role });
            return await db.SaveChangesAsync();
        }));
        Assert.Equal("ck_audit_event_actor", Assert.IsType<PostgresException>(error.InnerException).ConstraintName);
    }

    [Theory]
    [InlineData("actor_kind", "invalid", "ck_audit_event_actor_kind")]
    [InlineData("entity_type", "invalid", "ck_audit_event_entity_type")]
    [InlineData("action", "invalid", "ck_audit_event_action")]
    [InlineData("after_state", "[]", "ck_audit_event_after_state_object")]
    public async Task Database_rejects_invalid_storage_values(string column, string value, string constraint)
    {
        var error = await Assert.ThrowsAsync<PostgresException>(() => fixture.QueryAsync(async db =>
        {
            // Column comes only from the literal test cases above; all values remain parameters.
            var actor = column == "actor_kind" ? value : "cv";
            var entity = column == "entity_type" ? value : "work_order";
            var action = column == "action" ? value : "created";
            var after = column == "after_state" ? value : "{}";
            return await db.Database.ExecuteSqlInterpolatedAsync($"""
                INSERT INTO audit_event (actor_kind, commune_id, entity_type, entity_id, action, after_state, correlation_id)
                VALUES ({actor}, {fixture.CommuneId}, {entity}, 'WO-0001', {action}, {after}::jsonb, {correlationId})
                """);
        }));
        Assert.Equal(constraint, error.ConstraintName);
    }

    private Task<int> InsertAsync() => fixture.QueryAsync(async db =>
    {
        Writer(db).Record(Change(DateTime.UtcNow));
        return await db.SaveChangesAsync();
    });

    private Task<int> CountAsync() => fixture.QueryAsync(db => db.Set<AuditEvent>().IgnoreQueryFilters()
        .CountAsync(a => a.CorrelationId == correlationId));

    private AuditTrail Writer(LuxMapDbContext db) => new(db, new Correlation(correlationId));

    private AuditChange Change(DateTime now) => new(now, AuditActorKind.Cv, null, null,
        fixture.CommuneId, AuditEntityType.WorkOrder, "WO-0001", AuditAction.Created, null,
        new { WoStatus = WorkOrderStatus.InProgress, ObservedAt = now });

    private void SignIn(params string[] communeIds)
    {
        fixture.Services.GetRequiredService<IHttpContextAccessor>().HttpContext = new DefaultHttpContext
        {
            User = new ClaimsPrincipal(new ClaimsIdentity(
                communeIds.Select(id => new Claim(AuthClaims.CommuneIds, id)), "Test")),
        };
    }

    private sealed record Correlation(string CorrelationId) : ICorrelationIdAccessor;
}
