using LuxMap.Persistence.Conventions;
using LuxMap.Shared.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LuxMap.Api.Tests;

/// <summary>
/// An entity that exists ONLY in the test assembly (option (c)). No migration; the table is created
/// and dropped with raw SQL by <c>ScopeTestFixture</c>, so nothing is left behind in the project's
/// migration history.
/// </summary>
/// <remarks>
/// <c>CommuneId</c> is an ORDINARY indexed column, exactly as <c>Pole</c> will have it in BE-09 —
/// unlike <c>AdministrativeUnit</c>, where <c>commune_id</c> is the primary key and filtering on the
/// key is a degenerate case that would not catch a real bug.
/// </remarks>
public class ScopeProbe : ICommuneScoped
{
    public long Id { get; set; }

    public required string Label { get; set; }

    public required string CommuneId { get; set; }
}

public sealed class ScopeProbeConfiguration : IEntityTypeConfiguration<ScopeProbe>
{
    public void Configure(EntityTypeBuilder<ScopeProbe> builder)
    {
        builder.ToTable(ScopeProbeSchema.TableName);
        builder.HasKey(probe => probe.Id);
        builder.Property(probe => probe.Id).ValueGeneratedOnAdd();
        builder.Property(probe => probe.Label).HasColumnType("text").IsRequired();
        builder.HasIndex(probe => probe.CommuneId);

        // Two lines, two startup guards, and removing either stops the application booting:
        // HasCommuneScope satisfies the ICommuneScoped guard, HasCommuneReference satisfies the one
        // that scans for a commune_id column without a foreign key.
        builder.HasCommuneScope();
        builder.HasCommuneReference(probe => probe.CommuneId);
    }
}

public static class ScopeProbeSchema
{
    public const string TableName = "scope_probe_test_only";

    public const string CreateSql = $"""
        CREATE TABLE IF NOT EXISTS {TableName} (
            id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            label       text NOT NULL,
            commune_id  text NOT NULL REFERENCES administrative_unit (commune_id) ON DELETE RESTRICT
        );
        CREATE INDEX IF NOT EXISTS ix_{TableName}_commune_id ON {TableName} (commune_id);
        """;

    public const string DropSql = $"DROP TABLE IF EXISTS {TableName};";
}
