using LuxMap.Persistence.Conventions;
using LuxMap.Shared.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LuxMap.Api.Tests;

/// <summary>
/// Entity CHỈ tồn tại trong assembly test (phương án (c)). Không có migration; bảng do
/// <c>ScopeTestFixture</c> tạo và xoá bằng SQL thô, nên không để lại gì trong migration history
/// của dự án.
/// </summary>
/// <remarks>
/// <c>CommuneId</c> là cột THƯỜNG có index, giống hệt cách <c>Pole</c> sẽ có ở BE-09 — khác
/// <c>AdministrativeUnit</c> nơi <c>commune_id</c> là khoá chính, lọc trên khoá chính là ca suy
/// biến không bắt được lỗi thật.
/// </remarks>
public class ScopeProbe : ICommuneScoped
{
    public long Id { get; set; }

    public required string Label { get; set; }

    public required string CommuneId { get; set; }
}

public sealed class ScopeProbeConfiguration : IEntityTypeConfiguration<ScopeProbe>
{
    public void Configure(EntityTypeBuilder<ScopeProbe> builder)
    {
        builder.ToTable(ScopeProbeSchema.TableName);
        builder.HasKey(probe => probe.Id);
        builder.Property(probe => probe.Id).ValueGeneratedOnAdd();
        builder.Property(probe => probe.Label).HasColumnType("text").IsRequired();
        builder.Property(probe => probe.CommuneId).HasColumnType("text").IsRequired();
        builder.HasIndex(probe => probe.CommuneId);

        // Đây là dòng mà chốt chặn lúc khởi động đòi hỏi. Bỏ nó đi thì app không boot.
        builder.HasCommuneScope();
    }
}

public static class ScopeProbeSchema
{
    public const string TableName = "scope_probe_test_only";

    public const string CreateSql = $"""
        CREATE TABLE IF NOT EXISTS {TableName} (
            id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            label       text NOT NULL,
            commune_id  text NOT NULL
        );
        CREATE INDEX IF NOT EXISTS ix_{TableName}_commune_id ON {TableName} (commune_id);
        """;

    public const string DropSql = $"DROP TABLE IF EXISTS {TableName};";
}
