using LuxMap.Shared.Authorization;
using LuxMap.Shared.Contracts.Enums;

namespace LuxMap.Modules.Survey.Entities;

/// <summary>
/// One illuminance measurement taken by a person with a meter. Its ID looks like <c>LUX-0001</c>
/// (Contract section 0.2).
/// </summary>
/// <remarks>
/// <b>This is NOT <c>luminance_history</c>, and confusing the two breaks the research.</b> Contract
/// section 2.9 calls lux readings the <b>ground truth for RQ1</b>: CV-12 scores the system's own
/// classification against them. They are two different measurements of the same pole:
/// <list type="bullet">
/// <item><b>LuxReading</b> — a human with a meter. <c>measured_at</c>, an ABSOLUTE
/// <c>lux_value</c>, <c>meter_model</c>.</item>
/// <item><b>luminance_history</b> (BE-15/BE-17 + CV) — computer vision over sweep imagery.
/// <c>observed_at</c>, <c>sweep_id</c>, a RATIO <c>baseline_ratio</c>, <c>classified_as</c>.</item>
/// </list>
/// Writing lux into the luminance series would make CV-12 mark its own homework, and would also
/// distort the BE-20 chart. They meet in exactly one place: the <c>nearest_luminance</c> field of
/// <c>GET /lux-readings</c>, paired by TIME within ±48 hours.
/// </remarks>
public class LuxReading : ICommuneScoped
{
    /// <summary>Generated by the database sequence — never assign it when inserting.</summary>
    public string LuxId { get; set; } = null!;

    /// <summary>
    /// Client-generated UUID, the de-duplication key of Contract section 5.8.
    /// </summary>
    /// <remarks>
    /// Unique index, and that is the real guard rather than a read-then-write check: two retries
    /// arriving together would both pass the check and both insert. A duplicate is answered with
    /// <b>200</b> and the existing record — a retry on a weak connection is normal behaviour in the
    /// field, not an error.
    /// </remarks>
    public required string ClientOpId { get; set; }

    /// <summary>
    /// The pole this was measured at. REQUIRED.
    /// </summary>
    /// <remarks>
    /// Contract section 2.9 has no required/optional table (section 2.8 does), so this was settled
    /// explicitly and recorded as drift. It is required because everything else in 2.9 depends on
    /// it: <c>GET /poles/{id}/lux-readings</c> is a series per pole, <c>nearest_luminance</c> pairs
    /// against "the same pole", and <see cref="CommuneId"/> is derived from it. The FO-07 calibration
    /// rig is registered as real poles (section 2.9), so rig measurements carry one too.
    /// </remarks>
    public required string PoleId { get; set; }

    /// <summary>
    /// Denormalised from <see cref="PoleId"/>'s pole. NEVER accepted from the client.
    /// </summary>
    /// <remarks>
    /// Without it this entity is outside <c>ICommuneScoped</c>, and therefore outside BOTH the query
    /// filter and the <c>SaveChanges</c> write guard — the whole of Contract section 7 would skip it.
    /// <para>
    /// ⚠️ The justification used on <c>Fixture</c> — "never returned as a resource of its own, so the
    /// extra column breaks no published shape" — does NOT apply here: LuxReading has its own
    /// endpoints. The column is kept out of the response instead, deliberately.
    /// </para>
    /// <para>
    /// The server reads it from the pole rather than taking it from the body. The write guard checks
    /// whether a commune is inside the caller's scope; it does NOT check that the value matches the
    /// pole's own commune. A caller could otherwise send their own commune with someone else's pole
    /// and pass both checks while filing the reading under the wrong commune.
    /// </para>
    /// </remarks>
    public required string CommuneId { get; set; }

    /// <summary>When the measurement was taken. <c>TIMESTAMPTZ</c>, always <c>DateTimeKind.Utc</c>.</summary>
    public DateTime MeasuredAt { get; set; }

    /// <summary>
    /// Illuminance in lux. Contract section 2.9: a real number, non-negative.
    /// </summary>
    /// <remarks>
    /// No upper bound, deliberately. The Contract sets none, and this is ground truth: rejecting a
    /// real measurement loses it permanently — FO-14 measures once, in the field — whereas an
    /// implausible value stays visible and can be excluded during analysis. Values above 200 lux are
    /// logged as a warning and stored unchanged.
    /// </remarks>
    public double LuxValue { get; set; }

    /// <summary>The instrument, e.g. <c>UNI-T UT383</c>. Part of reproducibility, not decoration.</summary>
    public string? MeterModel { get; set; }

    /// <summary>
    /// Which of Branch C's data sources this measurement belongs to. Required by Contract section 2.9.
    /// </summary>
    /// <remarks>
    /// Unlike <c>Pole</c> and <c>Fixture</c>, where <c>data_source</c> is stored but never emitted,
    /// here it IS part of the published body and IS returned — section 2.9 lists it in the request and
    /// as a filter on <c>GET /lux-readings</c>.
    /// </remarks>
    public DataSource DataSource { get; set; }

    public string? Note { get; set; }

    /// <summary>
    /// The user who recorded it, taken from the JWT.
    /// </summary>
    /// <remarks>
    /// Not in the Contract's request body and not in the response — the same shape as
    /// <c>reported_by</c> in section 2.8, which the server sets and the client cannot. The task list
    /// requires "người đo" to be stored; the Contract omits it entirely. Recorded as drift.
    /// <para>
    /// A real foreign key with <c>Restrict</c>, not free text: free text would record a name nobody
    /// can resolve back to an account, which is not traceability.
    /// </para>
    /// </remarks>
    public required string MeasuredBy { get; set; }

    public DateTime CreatedAt { get; set; }
}
